Concepts of function project
* notes, meetings, etc.
** 20191207 notes (meeting with Zach, Stefan, Josh, Paul)
Discussion of pilot study classification, in which Zach/Josh/Stefan classified some instances of function usages. We discussed the various ambiguities and problems we countered. Paul was also present (although he hadn't classified any himself)
   - explained will often be selected effects
   - genomic conflict implies evolution (202)
   - because biological advantage is a subset of causal role, there are two implications: (i) we'll tend to classify as causal role things that are implicitly biological advantages but not stated explicitly; and (ii) we'll classify as biological advantage things that are also causal roles (by giving precedence to biological advantage)
   - when seleciton or evolution is used in conjunction with a explanation for why something exists or varies, etc. we say it is selected effects
   - general: for selected effets, we'll often defer to phrases like "reproductive strageties", "sexual conflict", "sexual selection"
   - causal role is not default -- we'll add another category for unspecified or insufficient context
   - biological advantage needs an explicit, normative component (important that we don't infer a benefit if it is not explicitly stated)
   - for noun-phrases where the head noun is not a trait-like thing, and/or we can replace function with activity or performance, then we classify as unspecified (but need to check if )
   - another possibility is to turn a noun phrase of "x function" into "the function of x is..."
   - Zach brought up the potential ambiguitiy in a phrase like liver function, which might be used in the sense of "the function of the liver is..." (e.g. the function of the liver is either x or y) or in the sense of "the liver is functioning"  (i.e. the liver is performing its function vs. it being dysfunctional)
   - not worth recording positive/negative use of each function ascription (i.e. the difference between x had function y and x did not have function y).
*** actionable items
    - We need to add another "technical" definition (corresponding to "ambiguous", "undefined" or the like) for those functions ascriptions that contain insufficient evidence for classification
    - Classify as causal role when there is a connection between function and at least one identifiable effect in at least one containing system (although we are probably not too committed to the containing system assumption) but without an explicitly normative component
    - Classify as biological advantage when there is a causal role function that contains an explicitly normative component
    - Classify as selected effects when either (i) function is explicitly used in an evolutionary sense or connected to language associated with evolutionary theories (e.g. natural selection, sexual selection, kin selection, genetic conflict, sexual conflict, reproductive strategies, frequency-dependence, etc.) or (ii) function is connected with etiological or explanatory language (i.e. usages that connect a trait's function with the reason it exists).
*** still to address (will discuss with Monika on 20191209)
    - noun phrases--can we find a rule of thumb for dealing with these?
      + Rephrasing in a different form? E.g. x function as the function of x?
      + One difference between a phrase like "ecological function" compared to "liver function" is that in "ecological function" function is paired with an adjective that cannot act as a trait. Likewise, if it were instead "ecosystem function", although ecosystem is a noun, it isn't something we consider as a having a trait. We can have other phrases like "functional connectivity" where function is in the adjectival form functional but connectivity is not something we can consider as a trait. So one rule-based way out of this is might be to classify it as "undefined" when function is used as an adjective in a noun phrase and likewise when the noun phrase refers to something that we don't consider as being a trait.
      + If we have a sentence like "Liver function is affected by expression of gene A" then I think we can classify this as causal role because function is associated with a change in gene A expression. The sentence can be rewritten as "Expression of gene A affects the function of the liver", which implies that the function of the liver is dependent on gene A expression (i.e. gene A expression is a causal role function within system liver). Less obviously, it might also be rewritten as "Expression of gene A affects functioning of the liver", which could imply that healthy activity of the liver (i.e. not being in a dysfunctional state) depends on gene A. In this case, functioning of the liver depends on gene A expression (alternatively, gene A expression affects liver functioning). In this case, is gene A a causal role function in system liver? I think the answer is yes but acknowledge that this is a different case to liver function in the sense of "the function of the liver" (because there is a difference between the function-dysfunction distinction and the function1-function2 distinction). My reasoning is that if gene A  affects functioning(-as-opposed-to-dysfunctioning) of the liver, it must have a detectable effect in system liver and is therefore a causal role. This is something to discuss at the TMB meeting on 20191209.
    - *Note: I no longer believe the last paragraph to be a correct way of thinking* (see notes from meeting post three dimensions function presentation)
** 20191209 day agenda
   - 9:00-10:30 Introduce conceptual framework for three dimensions of function to TMB; get feedback on technical definitions (insufficient evidence, causal role, biological advantage, selected effects)
   - 10:30-11:30 TMB weekly meeting
   - 11:30-14:00 Zach compiles list of difficult cases from a linguistic standpoint to present to Monika (especially the various ways that function can be used in noun phrases); Josh works on data/text mining code
   - 14:00-15:00 Meet with Monika
   - 15:00- Zach compiles list of dois by searching and exporting from WoS; Josh, using full list of dois, starts running text mining code on desktop
TODOS for 20191209
  - [ ] ask Zach to also keep a version of the JCR subdiscpline ranking list that includes all the different subdiscipline labels (not just keeping the ones that are in the top 30 of their subdiscipline)
  - [ ] ask Zach to compile list of difficult cases from a linguistic standpoint to present to Monika (especially the various ways that function can be used in noun phrases)
  - [ ] ask Zach to compile list of dois by searching and exporting from WoS
TODOs for 20191210
  - [ ] compile another small dataset for a pilot study (from which we'll calculate inter-rater reliability)
** 20191209 (9:00 with TMB)
*** agenda
   - Quickly introduce project (including the two subprojects)
   - Describe the three types of function we consider: causal role, biological advantage, selected effects
   - Outline the conceptual framework
   - Discuss Garson's 3 desiderata and how under his view selected effects gets a lot for free (leading him to be, in my view, far too generous to selected effects)
   - Show how conceptual framework relates to Tinbergen's Qs and the proximate/ultimate distinction
*** notes from discussion
   - well received I think
   - noted that Tinbergen's Qs can map onto the same framework if you collapse his 3 and 4 into a single one. Paul pointed out that Huxley had apparently proposed this at some point (not sure of primarily literature, but apparently Tinbergen mentions this). This is quite nice as there is an easy mapping between the framework I proposed for function and Tinbergen/Huxley as well as proximate/ultimate (which should make it fairly palatable).
** 20190209 meeting post three dimensions of function presentation (me, Paul, Stefan, Zach)
   - we went through the "liver function" case again. In hindsight, my characterisation of it above was not accurate.
     + If "liver function is affected by expression of gene A", then the only reframing that's accurate is "gene A affects functioning of the liver". One could claim that this shows a causal role of gene A, but in this case, the use of "liver function" is almost incidental, as function could easily be replaced with performance, activity, etc. Liver function, in this sense, refers to the liver as a containing system /not/ the liver as having a function in a larger containing system (e.g. the hepatic system). The reason we can't talk of the liver as having a function in this sentence is because there is no reference to its role in a larger containing system.
   - We also had a quick discussion about "functioning" as implying a normative aspect. While I think this is reasonable, it's important that normativity here refers to the functional to dysfunctional continuum.
     + I would argue that this is different to normativity in the sense of "gene A's function" has a positive/negative effect in the containing system (i.e. the tipping point from causal role to biological advantage).
     + 20191212 note on the last point: these are clearly different notions of normativity. One is the functioning <-> dysfunction continuum, which relates to function in the sense of "perform as expected when applied"; the other is the CR <--> BR continuum, which relates to function in the sense of "does the effect convey an explicitly-identified advantage to the system"
** 20191209 (14:00 with Monika)
*** agenda
**** classification
    - how to deal with noun phrases? All three of us doing the classification (JR, ZW, SG) struggled with these. Zach will compile a list of tough cases for reference.
    - make functional (adjective) its own category?
    - what to do with usages like dysfunction, subfunctionalisation, etc.?
**** misc
    - inter-rater reliability--sample size for overlap of samples between ZW and SG (I think I'll get everyone involved to classify this subset)? I think we'll probably need to conduct another (small) pilot study to determine this since it will depend on variance in agreement. It would be good to run another quick pilot study with the new guidelines in any case to iron out any final problems.
    - is our choice for common membership of biological subdisciplines (if the appear in the top 30 for a given subdiscipline) the best way around the issue of journals having overlapping subdisciplines (e.g. ecology and evolutionary biology)? I'm also considering a method whereby I use document similarity to just apportion papers within these journals to a single subdiscpline.
    - should I extract from abstracts when full text is available? (Keeping in mind that I'm planning on excluding papers that only have abstracts available.)
**** Zach's CPC project
    - have a quick discussion of the methods that Zach will use in his CPC project analysis (collocation, frequency, etc.). Set up meeting between him and Monika for her to teach him how to use the software she uses.
*** meeting
    - unfortunately we weren't able to resolve this, as it is a tricker problem than I had perhaps realised
    - Monika made the point that we should clearly separate semantics and construction (i.e. we aren't so concerned about whether function is used in a noun phrase but rather its meaning in the noun phrase)
    - we will need to use a form of unpacking, whereby we rearrange sentences, substitute function for another word (e.g. activity, performance), etc. so as to get at the core meaning
*** actions
    - add adjective to noun and verb. Also record the specific form (I can pull the latter out automatically)
I think we just start with the additional categories below and refine as we find examples that don't fit
    - out of scope cases that ascribe function to entites at the organismal level or higher (e.g. organisms, groups, ecosystems) or cases that define the containing system as higher than the organism (e.g. groups, ecosystems)
    - cases that use function in a narrow, technical sense
    - cases that use function as synonymous with activity or performance (in which case it is a characteristic of the containing system not the trait)
    - others?
** 20191210
Zach and I went through some ways of how we might classify function when used as 
** 20191211 (14:00 meeting with Joel)
*** agenda
   - classification of entire documents into subdiscplines using supervised or semi-supervised approaches (would apply to general science journals, general biology journals, and possibly journals with dual categories [note that in the latter case, I will want to classify between ALL the subdiscipline labels, not just those in the top 30]). The "labelled samples" would be full texts from journals that are members of a single subdiscipline (according to Incites). General science/biology could be classified into any subdiscipline while journals that are members of multiple subdisciplines could be classified into one of these subdisciplines.
   - unsupervised or semi-supervised clustering, maybe using attention model, to see how well I can categorise labelled samples (compared to a supervised approach using BERT transfer-trained on function wsd)
   - Can I combine wordnet synsets (e.g. serve, officiate) to create a custom dictionary without issues? Should be fine but just want to check as I'm planning on first training BERT on wordnet then again on my "function dictionary"
   - training/test set split and how this should relate to the inter-rater reliability set
*** meeting
   - suggested that I get sentences (would prevent truncation in the case of a very long sentence). Might use something like max(x, length(before + sentence + after))
   - inter coder agreement: could assign in pairwise manner also (so long as there is overlap between all three pairs). I will also randomize each person's order to guard against drift.
   - he didn't think that unsupervised or semi-supervised approaches would have much chance. Brett seemed to think that they might. I'm not sure but I'll at least start with the supervised and see how things progress.
   - for the subdiscipline analysis, probably just limit the analysis to samples from the subdisciplines (i.e. exclude papers from the general biology and general science category for this part)
   - can test that prediction is robust to selection of training set (bagging)
** Some thoughts about the rough number of samples we'll get
*** Labelled
    Very hard to estimate, but perhaps Zach will get around 5,000 classifications falling within the three technical categories (2 per minute, 300 minutes per day for 15 days (9000) with a decent chunk, but less than half, falling into "insufficient evidence"). 
At this point, I'm not sure how much time Stefan will have (and some of these will be redundant for inter-rater reliability purposes), but I suppose we'll end up with 5,000-10,000 labelled samples in the three technical categories (and 10,000--20,000 labelled samples overall).
*** Total
    We'll have roughly 250k papers in the corpus of which half might have full texts (wild guess) with probably 20+ mentions of function per paper on average, giving something like 3 million+ individual usages.
Of these, I suspect substantially fewer than half will fit into the 3 categories.
Note that this is lower than my estimate for the labelled samples because our labelled samples will be evenly distributed across papers.
(Some papers contain 100+ usages of noun phrases like "ecosystem function", "functional connectivity", etc., which would cause the proportion of "insufficient evidence" cases to be higher in the total sample.)
** useful packages
   - https://github.com/allenai/scispacy (tokenisation optimised for scientific papers)
   - https://arxiv.org/pdf/1903.10676.pdf (scibert -- transfer learning on general scientific papers)
   - https://github.com/dmis-lab/biobert (biobert -- transfer learning on biomedical papers)
   - https://arxiv.org/abs/1908.07245 (glossbert -- transfer learning for wsd on SemCor3.0)
** 20191212 (unpacking functional)
*** general structure of "functional" clauses
    - functional <concrete noun> (e.g. "functional trait", "functional gene"--these are still fairly abstract, but in theory they refer to something physical). Functional can be used here to modify a  "component" of the system. I don't think we'll encounter it in this form so often though (more likely to be of the form "the <concrete noun> was functional"
    - functional <abstract noun> (e.g. "functional effects", "functional importance"). Functional here isn't directly modifying a noun that can refer to a component (we can't talk of the trait "effects" having the function to do x in y")
*** draft approach
    1. Identify the noun that functional modifies
    2. Assume that the noun is the component of the system
       2.1. Rearrange the sentence into the form "The function of <noun> is to do..."
       2.2. Does it make any sense whatsoever (it won't if the noun is abstract)? If not, go to 3.
       2.3. If yes, can we identify the effect and system?
       2.4. If no, unspecified. If yes, candidate for CR, BA, SE.
    3. Is the use of functional technical? If yes, classify as technical use of function; if not go to 4.
    4. (Assuming functional is now abstract.) Can we identify a concrete noun that functional <abstract noun> refers to?
       4.1. If no, unspecified. If yes, rearrange the sentence into the form "The function of <concrete noun> is to do..." (for the moment effectively just treating the <abstract noun> as irrelevant)
       4.2. Can we identify the effect and system?
       4.3. If no, unspecified. If yes, candidate for CR, BA, SE.

How does functional as functioning fit into here? It's clearly possible to have a phrase like "the functional gene" meaning "the gene that is functioning".
*** revised approach
    1. Is functional used in a technical sense? If yes, *technical use of function*. If not, go to 2.
    2. Identify the noun that functional modifies. Go to 3.
    3. Assume that the noun is the component of the system
       3.1. Rearrange the sentence into the form "The function of <noun> is to..."
       3.2. Does it make sense (i.e. is <noun> sufficiently concrete)? If so, go to 3.3; if not, go to 4.
       3.3. If yes, can we identify the effect and system?
       3.4. If no, either incompletely specified, used to mean functioning/activity, or an abstract noun; go to 4. If yes, either *CR*, *BA*, or *SE*.
    4. Can we identify a "concrete" noun that functional <abstract noun> refers to? If yes, go to 4.1; if no, go to 5.
       4.1. Rearrange the sentence into the form "The function of <concrete noun> is to..." (note, this implies that the abstract noun is unimportant...are there cases where this is violated?)
       4.2. Can we identify the effect and system?
       4.3. If no, (either go to 5). If yes, either *CR*, *BA*, or *SE*.
    5. Is function being used in the sense of functioning or is it unspecified? (Need to write protocol for distinguishing this from the standard noun phrase case).

This will need to be refined. I need to integrate into it the distinction between incompletely specified and function in the sense of functioning. I should also perhaps distinguish between the different ways of being incompletly specified (the two I can think of right now are (i) not having an identifiable effect; (ii) can't manipulate into canonical form)

*** questions for Paul
    - dysfunction (I think we just call this function in the sense of working, activity, performance, etc.
    - Differentiating CR and BA (what reaches the threshold for normative language?) How much do we want to restrict BA to fitness effects (i.e. normative judgements on system "organism" relating to reproductive output)? Relevant here is the distinction between criteria for biological advantage as a document level classification (this is how biologists are generally talking about function in this paper) vs. a sentence level classification.
    - Is it okay if the system is implied (which means in practice we ignore it)?
    - Okay to restrict containing systems to organisms or smaller (thereby excluding ecology)?
*** meeting
    - will lump dysfunction into the perform/work category
    - not sure we had a complete resolution of the CR vs BA but the general feeling is that we need to see two things: (i) an /explicit/ normative aspect applied to the functioning of the system (as a result of the function of the component) and (ii) we can draw an /implicit/ connection between functioning of the system and an organismal-level advantage/disadvantage. For example, "gene A functions to improve metabolic efficiency in mice" ("improve metabolic efficiency" is explicitly normative and implicitly beneficial for the organism (improved metabolism = better utilisation of energy = competitive advantage = more offspring). (This is admittedly still a bit vague since the postulated connection between improved metabolism and increased offspring production is  tenuous (e.g. increased metabolic efficiency = less generated heat = potential disadvantages) but the key here is not that we can show that it leads to more offspring but rather that the evaluative language on system-level effects could impact in some way---positive or negative---on offspring production).
    - agreed that there is a distinction between document-level classification and sentence-level classification, but in practice we are limited by what we can do here. I think one might make a case that a document that has a classification set of something like 8 CR instances, 2 BA advantage instances is talking about function in a biological advantage sense (generally using CR but makes the connection between CR and BA). So we might use some general rule to classify documents, but clearly any document-level classification scheme that people have previously used is qualitative (it doesn't make sense to label a document as either CR or BA or SE---clearly there is a meaningful difference between a paper with 9CR/1BA and one with 1CR/9BA even though they both have CR/BA instances.) Should also note that it is entirely possible that a connection between something having a causal role function and it also having a biological advantage could be made somewhat indirectly in a way that we wouldn't pick up (e.g. by using words other than function and/or addressing this in a separate part of the paper)
    - will have to think about nominative phrases such as "secretory function" where there is an adj but not function(al). Slightly different to a nominative phrase like secretion function but I think we just unpack using the same general approach "secretions function to..."
      + also have to consider functionality, functionally, etc.
    - Fine to restrict to biological usage (i.e. containing system as organism or lower; component as lower than organism)
    - Fine if containing system is implied
** random notes
   - for the conceptual angle, I nee dto think about Wouter's distinction between traits and items/behaviours and how this relates to our talk of characters and character states in the programmatic paper.
   - It's important to highlight the limitations of requiring everything to exist in a single sentence. A document-level classification would no doubt lead to different results (e.g. there might be many CR mentions but a single use of BA, which might make the document-level classification one of BA. Likewise, a BA mention might occur elsewhere in the paper, unattached to the word function, in which case we won't pick it up. We'll just have to mention this as a limitation.
** check publishers for fulltext access via get_full_texts.R
*** Wiley                                                           :WORKING:
*** Elsevier                                                        :WORKING:
*** Springer Nature
**** Nature                                    :BROKEN:curlpdfYES:curlxmlYES:
**** Nature research journals
**** Nature published (but not branded) journals
*** Oxford University Press
*** American Association for the Advancement of Science
*** Annual Reviews
*** Springer
Royal Society
Cold Spring Harbor Lab Press
American Soc Microbiology
Public Library Science
Taylor & Francis Inc
American Physiological Society
American Society of Plant Biologists
Frontiers Media SA
CSIRO Publishing
BMC
Royal Society of Chemistry
eLife Sciences Publications ltd.
National Academy of Sciences
University Chicago Press
Cambridge University Press
BMJ Publishing Group
Wolters Kluwer
Microbiology Society
Rockefeller University Press
Human Kinetics Publishers
Canadian Science Publsihing, NRC Research Press
American Chemical Society
Crop Science Society of America
Institute of Malacology
Brill
American Psychological Association


** restarting with Stefan
Zach finished up his CPC project and due to uncertainty around covid (and me having to focus on other projects) this project got put on hold for a couple of months. Am now restarting with Stefan. Due to uncertainty as to how much time I will have to commit to this project, I am reducing the project's scope somewhat. For starters, I will restrict the corpus to Elsevier and Wiley journals---I simply don't have time to write the code required to download full texts from 30+ different publishers, each with their own peculiarities. Some just seem impossible (e.g. OUP has theirs behind another provider (silverchair), which leads to security issues and I've been waiting for like 6 months for them to get back to me about permission to datamine). Unfortunately, Elsevier and Wiley are the only publishers with rock-solid APIs; fortunately (well for me in this case, certainly not for the world!), they are the two biggest publishers of the journals on the list. So I can still get very good coverage of the different fields even restricting to Elsevier and Wiley. Ultimately, it's better to complete an imperfect project than to design a perfect but unworkable project. Since I can't be sure that I will have time to do the NLP component, I will run this in a modular way. For example, once I have the corpus (and we've settled on the handbook), I can choose a random stratified sample set of papers for labelling. I can then download only those papers, extract all function instances from them, and choose a single one for labelling. If it turns out that I can complete the NLP portion, I can then download the rest of the papers and extract all the usages of function.
  - [X] Get Stefan to redo the list of journals. We'll now exclude general science and general biology (basically no Elsevier/Wiley and simplifies the issues with assigning to different subfields). We'll include the ten top journals for each subfield (from Elsevier/Wiley journals). For most, we can obtain that from the existing 30; for one or two subfields, it will require couple new journals to be added to the list. Journals that are multiply tagged with valid subfields (e.g. a journal tagged with genetics and plant sciences), will be members of all of those subfields. Any analysis wrt subfields will take place on all papers from journals tagged with that subfield (even if they did not show up in the top 10 of that subfield---this is possible because some subfields have journals with lower impact factors). There will likely be fewer than 80 journals (8 categories, 10 journals per category) in total, as some journals will be present in multiple categories.
  - [ ] Search on Web of Science for "function*", restricting to the journals identified above. These papers will define the corpus. Download metadata for corpus.
** 20200805 meeting with Stefan
We went through some examples to identify some issues with the handbook.
  - [X] 2.1 needs to be a little clearer with 'amod' -- function needs to be an amod of a noun (its head) rather than having an amod of itself.
  - [X] 2.2 right now it requires that the noun be an 'nsubj' but clearly this won't always be the case. If function is a head noun used in the predicate for example (I think this was what caused some confusion about how to answer 2.1)
  - [X] 2.5 example 13 (tab 2) has a case where it seems completely arbitrary as to which nmod path you follow from function---need to figure out an order of precedence here.
    + after playing around with this, I think it's a parsing error. I don't think both paths should be `nmod` out of "roles" -- that is not to say that it is not possible however.
  - [X] 3 it's not clear how to deal with y when function is a noun but isn't an nsubj. Oftentimes (always?) this will mean that there is no y (e.g. if function is a 'dobj') but the guidelines need to be clearer.
    + I have added a switch that if function is a dobj then y can't be identified. I think the best approach is to see whether this always holds up when we test it with examples.
** addition of basic logic
just a quick note that we'll need to implement a basic logic system for semantic parsing. 
Best to keep it simple, e.g. term (aristotelian) logic would suffice (all /x/ are /y/, some /x/ are /y/, all /x/ are not /y/, some /x/ are not /y/). 
In practice this will have little effect. It's mainly necessary for being explicit about negation.
I think it's acceptable to conflate all/some, seeing as science is largely about running "ideally designed" experiments such that one can generalise and claim that a demonstration of some /x/ being /y/ implies that, generally speaking, /x/s are /y/s.
** 20200909 meeting with Stefan
2.1 functionality of the gene as example is wrong because arrow goes wrong way (here functionality is the head so I think this should be 2.2)
- logic system (possibly, might be, etc.) as well as negation and all/some
** 20201125 meeting with Stefan
[25/11/2020 00:49] Joshua Christie
- Just some minutes for the record. We discussed how we want to keep the paper as simple as possible due to time constraints. This means using few examples and using simple examples (i.e. not convoluted text). Where possible we should focus on medical ones, given the topic of the paper. I thought that we might simplify section 5 (performing function...) because a lot of the subcategories are either meaningless (performing function as biological activity doesn't even make sense since there's no normative basis for saying that a trait "ought to" perform a biological activity). We could try to just centre it around performing a functional effect (where the functional effect has a normative basis). I thought it perhaps best to completely sidestep the issues with "drawing a line" between cases of biological advantage and selected effect by not providing any examples (and just noting how one might go about tackling this problem in the discussion). Instead Stefan could just start off with a simple biological activity/role and then we could go into two examples of performing function (one using a word that marks normativity like "dysfunction" or "malfunction" and another using a different type of normativity indicator). In general, I think the introduction and concluding sections should focus more on the functional--dysfunctional continuum as ultimately this is the one major addition we're making to Wouter's 2003 scheme. We can save time/space by mostly deferring to previous work for the function as activity/role/advantage/SE and focus more on the performing as ... bit (ultimately we're also contributing to Wouter's scheme by providing a formal framework for analysing sentences).
​[25/11/2020 00:54] Joshua Christie
- Something additional that we didn't discuss but it would be interesting for you to keep an eye on: do we get cases of "performing function as ..." where there's no normative basis? This might not make sense from a philosophical point of view but it doesn't mean that biologists don't use it. Or we might encounter cases where the normative basis is present but rather weak (e.g. we expect that some region of DNA is expressed because we've seen DNA with similar structure being expressed in other organisms. To my mind there's no philosophical grounding for this but I'm pretty sure it happens. It's one of the criteria that ENCODE used in their infamous 2012 nature paper on functional genomic elements. https://www.nature.com/articles/nature11247. Might be worth reading through this and seeing whether you find some interesting examples
** 20210212 meeting with Stefan
*** TODO josh
    - [ ] simplify the flowchart
    - [ ] write the introduction
*** TODO stefan
    - [ ] write up a draft on the first simple example (biological role)
    - [ ] write up a second simple example to demonstrate function as performing
    - [ ] find a good example for the dysfunction/malfunction and write up a synopsis
      for each example, write some bullet points of how you traverse the flowchart (with short justification for each step). For the performing as cases, then finish with a discussion of their normative basis.
*** next step (in 2 weeks)
Stefan can turn the word flowchart into a diagrammatic one for a figure for the paper
Stefan can work on the fourth example
Josh will start writing the discussion/conclusion
** 20210226 meeting with Stefan
Next meeting 05/03/2021
*** TODO Stefan [0/4]
    - [ ] Upload  ipynb file to google drive folder
    - [ ] change first example (drosophila) to one from ENCODE
    - [ ] flesh out the performing biological role (CRF release) and dysfunction examples
    - [ ] find two examples of "other normativity"
*** TODO Josh [0/3]
    - [ ] set up github repo so that Stefan can also use it
    - [ ] finish draft of introduction
    - [ ] redo flow chart (remove the distinction between the different "performing function as"

      
** 20210313 meeting with Stefan
We went through various examples from the elife paper's csv, identifying some problems.
The main take home messages were:
    - *some of the instructions in the flowchart are too specific* (e.g. looking for an xcomp relationship). We encountered several examples that retained the spirit (e.g. follow an arrow in this direction) but to which we could not apply these specific rules. These rules need to be made a bit more general (with some of the specifics treated as examples).
    - *the flowchart doesn't handle some fairly common cases well*. For example, one case is when function is `dobj` there's no way to follow the flowchart through the finite verb to get x (which would be `nsubj`). There are a couple of other cases that I need to add to the flowchart.
    - *each decision point in the flowchart needs to have a header* (i.e. a short phrase that decribes what it is trying to accomplish). There are a couple of reasons to do this: (i) it will force me to describe the goal of each step, which will hopefully help me generalise the flowchart description; (ii) these phrases can be used for the bubble flowchart in the paper; (iii) it gives some guidance as to how one might apply their own intuition if the flowchart fails for a particular example (e.g. you know you need to find /x/, can't get there via the flowchart, but can identify it from the sentence)
    - *need to shift focus of paper*. There are a couple of points to make here. We need to make it clear that this is not a finished handbook but rather a work-in-progress. In order to make it more robust, we would need to test it against many more examples, iterating as we go. Therefore, it makes sense for us to focus the bulk of the paper on showing how this scheme helps us with some complicated example (i.e. yes we admit that the scheme is a work-in-progress, but it already helps clarify a number of complicated examples. As a corollary, I think we should shift away from the focus on functional-dysfunctional (we obviously need to mention that this is the main one for disease, but I don't think the paper needs to be centered around this). It also means that I should remove almost everything about the theoretical basis behind concepts of function (e.g. everything to do with Tinbergen, tokens/characters, etc. (other than in the most broad sense for this latter case).)
** specific problems identified in 20210313 meeting
   1. When function is the direct object (`dobj`), there's currently no way to identify the `nsubj` as /x/ (to do this, we need to go through the finite verb). An example is elife-14. I think I can fix this by just adding this to step 2.5. Another example is elife-5, although here function isn't in the direct object but a dependency of the finite verb via `conj`.
   2. In a couple cases, the `dobj` is clearly too narrow. I think we mostly want to talk of it being a dependent of the finite verb (i.e. tail-to-head arrow). For example, elife-5 function is a dependent of the finite verb via `conj` (the finite verb is transitive and takes a direct object but functional isn't in this part of the clause). I believe some possible dependency relationships here are `dobj`, `conj`, `xcomp`, `ccomp`. This definitely applies to steps 3.2 and 3.3 but possibly to others as well.
   3. The description for 2.1 is not exhaustive so either needs to be made more general or I need to rethink about how to direct which path it goes through here (e.g. 2.1 could become the final "pool" if I want it to be "everything that isn't a noun or a verb). E.g. elife-5 has functional as adjective that modifies a verb (should go to 2.3 but currently goes to 2.2).
   4. The description of 3.1 is also a bit complicated---worth starting with verb and just letting everything else go to 3.2.
   5a. The description of 3.3 seems too restrictive (does this have to be via `nsubj`?; does the verb have to be transitive? I don't think so, I think what matters is that the verb has a dependency itself (i.e. arrow from tail to head)). Furthermore, when identifying /y/ this needs far more (general) instruction (/y/ isn't just the finite verb + dobj, it could be the finite verb plus any (or a combination of) its dependencies. e.g. "These results strongly indicate that many small proteins adopt three-dimensional structures and are fully functional, playing important roles in transcriptional regulation, cell signaling and metabolism.". One could reasonably construct /y/ as "adopts three dimensional structures", "play important roles in transcriptional regulation", "play important roles in cell signaling", or "play important roles in metabolism". (Note that 3.3 should thus note that it's possible to identify multiple /y/s; if so, one should complete the rest of the tree separately for each one. But Maybe the same could apply to x? e.g. proteins and genes have important functions for regulation? So I think I should make a metanote that if there are multiple xs, ys, etc. then one should work through all possibilities in a full factorial manner.
   5b. Note that y doesn't even have to include the finite verb, as it might include a clause modifying the verb that is a dependency of the finite verb. With elife-5, there's an xcomp from "adopt" to the clause starting with "playing". With my altered version of elife-5 (test = nlp("These results strongly indicate that many small proteins are robust and functional, playing important roles in transcriptional regulation, cell signaling and metabolism.")), there's a advcl from robust(are) to playing. In both cases, the playing clause contains key information about /y/.
   6. As I was playing around with elife-5, I also noticed that we can run into the case where a copula is the finite verb but since copulas are considered aux in UD, a ADJ is the head of the sentence (ROOT). I might need to add a note somewhere about this when identifying the finite verb. For test = nlp("These results strongly indicate that many small proteins are robust and functional, playing important roles in transcriptional regulation, cell signaling and metabolism.") we want to get from "functional" -> "robust" and then from "robust" to the copula "are". Note that it's not as simple as following the arrow from head to tail from functional (i.e. traversing dependencies until we find what functional depends on) and then going from tail to head from "robust", as this could also point us to "indicate", which is not what we want.
   7. Just a note that when you have to identify x by going "through" a verb (head to tail from function until you hit a finite verb/copula and then tail to head), we might need to take a separate path than 3.1. I'm not sure that 3.2 is particularly robust to non-trivial paths from function to the head noun (i.e. something like protein function). This particular example might be okay actually, as I think /x/ will generally be the subject---although from 3.2 it isn't clear whether you should start at /x/ or somewhere else---but I think there were other cases I encountered where if you have to keep following dependency arrows then 3.2 doesn't work well unless you go back to what function is a direct dependency of. Just something to keep in mind that I might need to expand these paths a bit. Note that test=nlp("The gene is not utilised, indicating that it is not functional because it is not transcribed.") is a useful example for thinking about what noun to start with in 3.2. If possible, try to start from /x/, as it is simpler to describe and makes more sense. I think we should at least start with this and if it doesn't work then we can add instructions to then start with the noun of which function was a more direct dependency.
   8. for identifying /z/, might also be nmod from noun (i.e. doesn't have to be a dependency of the verb). In fact there are so many combinations that this might take that I think it's probably better to just make it purely semantic (i.e. the answer to sample questions) rather than syntactic.
** other specific problems
   1. 3.4 can't deal with passive voice (e.g. "genes are transcribed, suggesting that they are functional").
      a passive subject (nsubjpass) is having something done to it and so acts a bit like an object
      I think 3.4 needs a switch for passive subjects in which you just look at the finite verb phrase
   2. need to handle test=nlp("The gene is not utilised, indicating that it is not functional because it is not transcribed.")
   3. I think the case in footnote 9 (dobj) is too specific for a redirect
# in footnote 9 of the flowchart, I say that if x is a dobj then we can't identify y
# that seems pretty reasonable but I'm a bit thrown off by the nsubjpass case, as here x is acting a bit like an object
# can i construct a case that falsifies footnote 9?
test=nlp("Ribosomes aid the translation of functional transcripts")
visualise(test)
test=nlp("Ribosomes aid the translation of functional transcripts into proteins")
visualise(test)
"""
so here we would have x as transcripts, which is in the predicate (not a direct object but for our purposes the same thing
as we can go aid -> translation (via dojb) -> transcripts)
so, according to footnote 9 we shouldn't be able to identify y
but shouldn't translation (or translation into proteins for the second case) be y?
this basically gets at whether we allow the unpacking to have the form of
the function of x is to be y-ed
if so, we have the function of transcripts is to be translated into proteins
This seems completely right in this case
But of course, footnote 9 isn't dealin with anything in the predicate but specifically with dobj
this isn't a case of x being in the dobj, so I might be wrongly attacking footnote 9.
Perhaps the bigger question here is whether something as specific as whether x has a dobj dependency should be in the flowchart
I tend to think it shouldn't
"""
  4. not the biggest issue, but there's a redundancy in the flowchart in step 4. If you go 4.2 and answer yes then you can go 4.3 -> 4.4 -> 4.5, so it's possible to end up at 4.5 by answering no to 4.2 even though you go to 4.5 if you answer yes to 4.2 (basically if you answer yes to 4.2 it can't answer yes to 4.5
     
