Three-dimensions of function text-mining project
* First stage (pilot study)
Zach has compiled the list of journals that we will search in (hopefully via Crossref) to get our corpus.
I have sent the list of publishers and journals off to the university library, and they will get back to me about licensing agreements, etc.
Zach has extracted the "function" phrases from a couple of papers.
(The original plan was to go through 45 different papers from the nine different categories (one from each of the top five journals in a category), but we'll have to see how we go for time.)
Eventually, I will fully automate the processing of full texts (extraction of function sentences, context, and other metadata), but for now I just want to quickly partially automate it, to save Zach the time of having to manually process papers. For starters, I will use grobid with xml.etree.ElementTree.
* Issues that need resolving before starting "real" study
  - [ ] What to do about noun phrases that include function (e.g. functional connectivity, functional biology)?
  - [ ] What to do about sentences that contain multiple instances of function?
  - [ ] What to do about inflected variants of function (e.g. functional, functions, dysfunction, subfunctionalisation, etc.)?
  - [ ] How to address overlap between of context between different instances of function (e.g. where two sentences in a row use function, the sentence after (for the first) and the sentence before (for the second) will also contain function)?
  - [ ] Is our current method, in which we attribute partial "subdiscipline" membership for any journal that falls within the top 30 journals of more than one subcategory, appropriate?
  - [ ] Is keeping one sentence before and after the use of "function" the best method? Should we make it x words before and after? This would remove the issue with having multiple uses of function in a single sentence (but might exacerbate the interference between context of multiple uses of function).
** 20191207 notes (meeting with Zach, Stefan, Josh, Paul)
Discussion of pilot study classification, in which Zach/Josh/Stefan classified some instances of function usages. We discussed the various ambiguities and problems we countered. Paul was also present (although he hadn't classified any himself)
   - explained will often be selected effects
   - genomic conflict implies evolution (202)
   - because biological advantage is a subset of causal role, there are two implications: (i) we'll tend to classify as causal role things that are implicitly biological advantages but not stated explicitly; and (ii) we'll classify as biological advantage things that are also causal roles (by giving precedence to biological advantage)
   - when seleciton or evolution is used in conjunction with a explanation for why something exists or varies, etc. we say it is selected effects
   - general: for selected effets, we'll often defer to phrases like "reproductive strageties", "sexual conflict", "sexual selection"
   - causal role is not default -- we'll add another category for unspecified or insufficient context
   - biological advantage needs an explicit, normative component (important that we don't infer a benefit if it is not explicitly stated)
   - for noun-phrases where the head noun is not a trait-like thing, and/or we can replace function with activity or performance, then we classify as unspecified (but need to check if )
   - another possibility is to turn a noun phrase of "x function" into "the function of x is..."
   - Zach brought up the potential ambiguitiy in a phrase like liver function, which might be used in the sense of "the function of the liver is..." (e.g. the function of the liver is either x or y) or in the sense of "the liver is functioning"  (i.e. the liver is performing its function vs. it being dysfunctional)
   - not worth recording positive/negative use of each function ascription (i.e. the difference between x had function y and x did not have function y).
*** actionable items
    - We need to add another "technical" definition (corresponding to "ambiguous", "undefined" or the like) for those functions ascriptions that contain insufficient evidence for classification
    - Classify as causal role when there is a connection between function and at least one identifiable effect in at least one containing system (although we are probably not too committed to the containing system assumption) but without an explicitly normative component
    - Classify as biological advantage when there is a causal role function that contains an explicitly normative component
    - Classify as selected effects when either (i) function is explicitly used in an evolutionary sense or connected to language associated with evolutionary theories (e.g. natural selection, sexual selection, kin selection, genetic conflict, sexual conflict, reproductive strategies, frequency-dependence, etc.) or (ii) function is connected with etiological or explanatory language (i.e. usages that connect a trait's function with the reason it exists).
*** still to address (will discuss with Monika on 20191209)
    - noun phrases--can we find a rule of thumb for dealing with these?
      + Rephrasing in a different form? E.g. x function as the function of x?
      + One difference between a phrase like "ecological function" compared to "liver function" is that in "ecological function" function is paired with an adjective that cannot act as a trait. Likewise, if it were instead "ecosystem function", although ecosystem is a noun, it isn't something we consider as a having a trait. We can have other phrases like "functional connectivity" where function is in the adjectival form functional but connectivity is not something we can consider as a trait. So one rule-based way out of this is might be to classify it as "undefined" when function is used as an adjective in a noun phrase and likewise when the noun phrase refers to something that we don't consider as being a trait.
      + If we have a sentence like "Liver function is affected by expression of gene A" then I think we can classify this as causal role because function is associated with a change in gene A expression. The sentence can be rewritten as "Expression of gene A affects the function of the liver", which implies that the function of the liver is dependent on gene A expression (i.e. gene A expression is a causal role function within system liver). Less obviously, it might also be rewritten as "Expression of gene A affects functioning of the liver", which could imply that healthy activity of the liver (i.e. not being in a dysfunctional state) depends on gene A. In this case, functioning of the liver depends on gene A expression (alternatively, gene A expression affects liver functioning). In this case, is gene A a causal role function in system liver? I think the answer is yes but acknowledge that this is a different case to liver function in the sense of "the function of the liver" (because there is a difference between the function-dysfunction distinction and the function1-function2 distinction). My reasoning is that if gene A  affects functioning(-as-opposed-to-dysfunctioning) of the liver, it must have a detectable effect in system liver and is therefore a causal role. This is something to discuss at the TMB meeting on 20191209.
    - *Note: I no longer believe the last paragraph to be a correct way of thinking* (see notes from meeting post three dimensions function presentation)
** 20191209 day agenda
   - 9:00-10:30 Introduce conceptual framework for three dimensions of function to TMB; get feedback on technical definitions (insufficient evidence, causal role, biological advantage, selected effects)
   - 10:30-11:30 TMB weekly meeting
   - 11:30-14:00 Zach compiles list of difficult cases from a linguistic standpoint to present to Monika (especially the various ways that function can be used in noun phrases); Josh works on data/text mining code
   - 14:00-15:00 Meet with Monika
   - 15:00- Zach compiles list of dois by searching and exporting from WoS; Josh, using full list of dois, starts running text mining code on desktop
TODOS for 20191209
  - [ ] ask Zach to also keep a version of the JCR subdiscpline ranking list that includes all the different subdiscipline labels (not just keeping the ones that are in the top 30 of their subdiscipline)
  - [ ] ask Zach to compile list of difficult cases from a linguistic standpoint to present to Monika (especially the various ways that function can be used in noun phrases)
  - [ ] ask Zach to compile list of dois by searching and exporting from WoS
TODOs for 20191210
  - [ ] compile another small dataset for a pilot study (from which we'll calculate inter-rater reliability)
** 20191209 (9:00 with TMB)
*** agenda
   - Quickly introduce project (including the two subprojects)
   - Describe the three types of function we consider: causal role, biological advantage, selected effects
   - Outline the conceptual framework
   - Discuss Garson's 3 desiderata and how under his view selected effects gets a lot for free (leading him to be, in my view, far too generous to selected effects)
   - Show how conceptual framework relates to Tinbergen's Qs and the proximate/ultimate distinction
*** notes from discussion
   - well received I think
   - noted that Tinbergen's Qs can map onto the same framework if you collapse his 3 and 4 into a single one. Paul pointed out that Huxley had apparently proposed this at some point (not sure of primarily literature, but apparently Tinbergen mentions this). This is quite nice as there is an easy mapping between the framework I proposed for function and Tinbergen/Huxley as well as proximate/ultimate (which should make it fairly palatable).
** 20190209 meeting post three dimensions of function presentation (me, Paul, Stefan, Zach)
   - we went through the "liver function" case again. In hindsight, my characterisation of it above was not accurate.
     + If "liver function is affected by expression of gene A", then the only reframing that's accurate is "gene A affects functioning of the liver". One could claim that this shows a causal role of gene A, but in this case, the use of "liver function" is almost incidental, as function could easily be replaced with performance, activity, etc. Liver function, in this sense, refers to the liver as a containing system /not/ the liver as having a function in a larger containing system (e.g. the hepatic system). The reason we can't talk of the liver as having a function in this sentence is because there is no reference to its role in a larger containing system.
   - We also had a quick discussion about "functioning" as implying a normative aspect. While I think this is reasonable, it's important that normativity here refers to the functional to dysfunctional continuum.
     + I would argue that this is different to normativity in the sense of "gene A's function" has a positive/negative effect in the containing system (i.e. the tipping point from causal role to biological advantage).
     + 20191212 note on the last point: these are clearly different notions of normativity. One is the functioning <-> dysfunction continuum, which relates to function in the sense of "perform as expected when applied"; the other is the CR <--> BR continuum, which relates to function in the sense of "does the effect convey an explicitly-identified advantage to the system"
** 20191209 (14:00 with Monika)
*** agenda
**** classification
    - how to deal with noun phrases? All three of us doing the classification (JR, ZW, SG) struggled with these. Zach will compile a list of tough cases for reference.
    - make functional (adjective) its own category?
    - what to do with usages like dysfunction, subfunctionalisation, etc.?
**** misc
    - inter-rater reliability--sample size for overlap of samples between ZW and SG (I think I'll get everyone involved to classify this subset)? I think we'll probably need to conduct another (small) pilot study to determine this since it will depend on variance in agreement. It would be good to run another quick pilot study with the new guidelines in any case to iron out any final problems.
    - is our choice for common membership of biological subdisciplines (if the appear in the top 30 for a given subdiscipline) the best way around the issue of journals having overlapping subdisciplines (e.g. ecology and evolutionary biology)? I'm also considering a method whereby I use document similarity to just apportion papers within these journals to a single subdiscpline.
    - should I extract from abstracts when full text is available? (Keeping in mind that I'm planning on excluding papers that only have abstracts available.)
**** Zach's CPC project
    - have a quick discussion of the methods that Zach will use in his CPC project analysis (collocation, frequency, etc.). Set up meeting between him and Monika for her to teach him how to use the software she uses.
*** meeting
    - unfortunately we weren't able to resolve this, as it is a tricker problem than I had perhaps realised
    - Monika made the point that we should clearly separate semantics and construction (i.e. we aren't so concerned about whether function is used in a noun phrase but rather its meaning in the noun phrase)
    - we will need to use a form of unpacking, whereby we rearrange sentences, substitute function for another word (e.g. activity, performance), etc. so as to get at the core meaning
*** actions
    - add adjective to noun and verb. Also record the specific form (I can pull the latter out automatically)
I think we just start with the additional categories below and refine as we find examples that don't fit
    - out of scope cases that ascribe function to entites at the organismal level or higher (e.g. organisms, groups, ecosystems) or cases that define the containing system as higher than the organism (e.g. groups, ecosystems)
    - cases that use function in a narrow, technical sense
    - cases that use function as synonymous with activity or performance (in which case it is a characteristic of the containing system not the trait)
    - others?
** 20191210
Zach and I went through some ways of how we might classify function when used as 
** 20191211 (14:00 meeting with Joel)
*** agenda
   - classification of entire documents into subdiscplines using supervised or semi-supervised approaches (would apply to general science journals, general biology journals, and possibly journals with dual categories [note that in the latter case, I will want to classify between ALL the subdiscipline labels, not just those in the top 30]). The "labelled samples" would be full texts from journals that are members of a single subdiscipline (according to Incites). General science/biology could be classified into any subdiscipline while journals that are members of multiple subdisciplines could be classified into one of these subdisciplines.
   - unsupervised or semi-supervised clustering, maybe using attention model, to see how well I can categorise labelled samples (compared to a supervised approach using BERT transfer-trained on function wsd)
   - Can I combine wordnet synsets (e.g. serve, officiate) to create a custom dictionary without issues? Should be fine but just want to check as I'm planning on first training BERT on wordnet then again on my "function dictionary"
   - training/test set split and how this should relate to the inter-rater reliability set
*** meeting
   - suggested that I get sentences (would prevent truncation in the case of a very long sentence). Might use something like max(x, length(before + sentence + after))
   - inter coder agreement: could assign in pairwise manner also (so long as there is overlap between all three pairs). I will also randomize each person's order to guard against drift.
   - he didn't think that unsupervised or semi-supervised approaches would have much chance. Brett seemed to think that they might. I'm not sure but I'll at least start with the supervised and see how things progress.
   - for the subdiscipline analysis, probably just limit the analysis to samples from the subdisciplines (i.e. exclude papers from the general biology and general science category for this part)
   - can test that prediction is robust to selection of training set (bagging)
** Some thoughts about the rough number of samples we'll get
*** Labelled
    Very hard to estimate, but perhaps Zach will get around 5,000 classifications falling within the three technical categories (2 per minute, 300 minutes per day for 15 days (9000) with a decent chunk, but less than half, falling into "insufficient evidence"). 
At this point, I'm not sure how much time Stefan will have (and some of these will be redundant for inter-rater reliability purposes), but I suppose we'll end up with 5,000-10,000 labelled samples in the three technical categories (and 10,000--20,000 labelled samples overall).
*** Total
    We'll have roughly 250k papers in the corpus of which half might have full texts (wild guess) with probably 20+ mentions of function per paper on average, giving something like 3 million+ individual usages.
Of these, I suspect substantially fewer than half will fit into the 3 categories.
Note that this is lower than my estimate for the labelled samples because our labelled samples will be evenly distributed across papers.
(Some papers contain 100+ usages of noun phrases like "ecosystem function", "functional connectivity", etc., which would cause the proportion of "insufficient evidence" cases to be higher in the total sample.)
** useful packages
   - https://github.com/allenai/scispacy (tokenisation optimised for scientific papers)
   - https://arxiv.org/pdf/1903.10676.pdf (scibert -- transfer learning on general scientific papers)
   - https://github.com/dmis-lab/biobert (biobert -- transfer learning on biomedical papers)
   - https://arxiv.org/abs/1908.07245 (glossbert -- transfer learning for wsd on SemCor3.0)
** 20191212 (unpacking functional)
*** general structure of "functional" clauses
    - functional <concrete noun> (e.g. "functional trait", "functional gene"--these are still fairly abstract, but in theory they refer to something physical). Functional can be used here to modify a  "component" of the system. I don't think we'll encounter it in this form so often though (more likely to be of the form "the <concrete noun> was functional"
    - functional <abstract noun> (e.g. "functional effects", "functional importance"). Functional here isn't directly modifying a noun that can refer to a component (we can't talk of the trait "effects" having the function to do x in y")
*** draft approach
    1. Identify the noun that functional modifies
    2. Assume that the noun is the component of the system
       2.1. Rearrange the sentence into the form "The function of <noun> is to do..."
       2.2. Does it make any sense whatsoever (it won't if the noun is abstract)? If not, go to 3.
       2.3. If yes, can we identify the effect and system?
       2.4. If no, unspecified. If yes, candidate for CR, BA, SE.
    3. Is the use of functional technical? If yes, classify as technical use of function; if not go to 4.
    4. (Assuming functional is now abstract.) Can we identify a concrete noun that functional <abstract noun> refers to?
       4.1. If no, unspecified. If yes, rearrange the sentence into the form "The function of <concrete noun> is to do..." (for the moment effectively just treating the <abstract noun> as irrelevant)
       4.2. Can we identify the effect and system?
       4.3. If no, unspecified. If yes, candidate for CR, BA, SE.

How does functional as functioning fit into here? It's clearly possible to have a phrase like "the functional gene" meaning "the gene that is functioning".
*** revised approach
    1. Is functional used in a technical sense? If yes, *technical use of function*. If not, go to 2.
    2. Identify the noun that functional modifies. Go to 3.
    3. Assume that the noun is the component of the system
       3.1. Rearrange the sentence into the form "The function of <noun> is to..."
       3.2. Does it make sense (i.e. is <noun> sufficiently concrete)? If so, go to 3.3; if not, go to 4.
       3.3. If yes, can we identify the effect and system?
       3.4. If no, either incompletely specified, used to mean functioning/activity, or an abstract noun; go to 4. If yes, either *CR*, *BA*, or *SE*.
    4. Can we identify a "concrete" noun that functional <abstract noun> refers to? If yes, go to 4.1; if no, go to 5.
       4.1. Rearrange the sentence into the form "The function of <concrete noun> is to..." (note, this implies that the abstract noun is unimportant...are there cases where this is violated?)
       4.2. Can we identify the effect and system?
       4.3. If no, (either go to 5). If yes, either *CR*, *BA*, or *SE*.
    5. Is function being used in the sense of functioning or is it unspecified? (Need to write protocol for distinguishing this from the standard noun phrase case).

This will need to be refined. I need to integrate into it the distinction between incompletely specified and function in the sense of functioning. I should also perhaps distinguish between the different ways of being incompletly specified (the two I can think of right now are (i) not having an identifiable effect; (ii) can't manipulate into canonical form)

*** questions for Paul
    - dysfunction (I think we just call this function in the sense of working, activity, performance, etc.
    - Differentiating CR and BA (what reaches the threshold for normative language?) How much do we want to restrict BA to fitness effects (i.e. normative judgements on system "organism" relating to reproductive output)? Relevant here is the distinction between criteria for biological advantage as a document level classification (this is how biologists are generally talking about function in this paper) vs. a sentence level classification.
    - Is it okay if the system is implied (which means in practice we ignore it)?
    - Okay to restrict containing systems to organisms or smaller (thereby excluding ecology)?
*** meeting
    - will lump dysfunction into the perform/work category
    - not sure we had a complete resolution of the CR vs BA but the general feeling is that we need to see two things: (i) an /explicit/ normative aspect applied to the functioning of the system (as a result of the function of the component) and (ii) we can draw an /implicit/ connection between functioning of the system and an organismal-level advantage/disadvantage. For example, "gene A functions to improve metabolic efficiency in mice" ("improve metabolic efficiency" is explicitly normative and implicitly beneficial for the organism (improved metabolism = better utilisation of energy = competitive advantage = more offspring). (This is admittedly still a bit vague since the postulated connection between improved metabolism and increased offspring production is  tenuous (e.g. increased metabolic efficiency = less generated heat = potential disadvantages) but the key here is not that we can show that it leads to more offspring but rather that the evaluative language on system-level effects could impact in some way---positive or negative---on offspring production).
    - agreed that there is a distinction between document-level classification and sentence-level classification, but in practice we are limited by what we can do here. I think one might make a case that a document that has a classification set of something like 8 CR instances, 2 BA advantage instances is talking about function in a biological advantage sense (generally using CR but makes the connection between CR and BA). So we might use some general rule to classify documents, but clearly any document-level classification scheme that people have previously used is qualitative (it doesn't make sense to label a document as either CR or BA or SE---clearly there is a meaningful difference between a paper with 9CR/1BA and one with 1CR/9BA even though they both have CR/BA instances.) Should also note that it is entirely possible that a connection between something having a causal role function and it also having a biological advantage could be made somewhat indirectly in a way that we wouldn't pick up (e.g. by using words other than function and/or addressing this in a separate part of the paper)
    - will have to think about nominative phrases such as "secretory function" where there is an adj but not function(al). Slightly different to a nominative phrase like secretion function but I think we just unpack using the same general approach "secretions function to..."
      + also have to consider functionality, functionally, etc.
    - Fine to restrict to biological usage (i.e. containing system as organism or lower; component as lower than organism)
    - Fine if containing system is implied
