#+TITLE: Three-dimensions of function

* Rough outline
Our goal is to understand how biologists use the word "function".
We are interested in a few things, including how researchers use "function", how this differs among subfields of biology, and how well use of function corresponds to the main philosophical views on biological function (we are also interested in how this has changed over time, how it is used in different sections of the text, how collocates differ, etc.).
* Definitions of function
Function is used in a variety of different ways, which makes this a particularly difficult word sense disambiguation problem.
We are of course primarily interested in the use of function in a manner consistent with philosophical or biological conceptions of function (as opposed to colloquial use).
Our starting point is the definitions of function in WordNet 3.1, which are:

Noun
1. S: (n) function, mathematical function, single-valued function, map, mapping ((mathematics) a mathematical relation such that each element of a given set (the domain of the function) is associated with an element of another set (the range of the function))

2. S: (n) function, purpose, role, use (what something is used for) "the function of an auger is to bore holes"; "ballet is beautiful but what use is it?"

3. S: (n) function, office, part, role (the actions and activities assigned to or required or expected of a person or group) "the function of a teacher"; "the government must do its part"; "play its role"

4. S: (n) function (a relation such that one thing is dependent on another) "height is a function of age"; "price is a function of supply and demand"

5. S: (n) function (a formal or official social gathering or ceremony) "it was a black-tie function"

6. S: (n) affair, occasion, social occasion, function, social function (a vaguely specified social event) "the party was quite an affair"; "an occasion arranged to honor the president"; "a seemingly endless round of social functions"

7. S: (n) routine, subroutine, subprogram, procedure, function (a set sequence of steps, part of larger computer program)

Verb
8. S: (v) function, work, operate, go, run (perform as expected when applied) "The washing machine won't go unless it's plugged in"; "Does this old car still run well?"; "This old radio doesn't work anymore"

9. S: (v) serve, function (serve a purpose, role, or function) "The tree stump serves as a table"; "The female students served as a control group"; "This table would serve very well"; "His freedom served him well"; "The table functions as a desk"

10. S: (v) officiate, function (perform duties attached to a particular office or place or function) "His wife officiated as his private secretary"

If we focus on semantics, and combine a couple of categories and parts of speech, then we can trim this to get:

  - (1). S: (n) (mathematics (a mathematical relation such that each element of a given set (the domain of the function) is associated with an element of another set (the range of the function)) *mathematical function*
  - (2, 3, 9, 10). S: (n, v) (what something is used for; actions expected of a thing; to serve a purpose; perform expected duties) *function as role or purpose*
  - (4). S: (n) (a relation such that one thing is dependent on another) *function as relation*
  - (5, 6). S: (n) (a social gathering) *function as social event*
  - (7). S: (n) (a set sequence of steps, part of larger computer program) *programming function*
  - (8). S: (v) (perform as expected when applied) *function as performing role or purpose*

The various technical definitions that I will introduce below generally fall broadly under *function as role or purpose*.
Likewise, there is a biological analogue to *function as performing role or purpose*.
To separate colloquial use from technical use, I will redefine these as *non-biological function as role or purpose* and *non-biological function as peforming role or purpose* to apply to non-biological usages (e.g. "The table functions as a desk").

To the colloquial definitions above, we add the technical definitions, which map onto the scheme in Wouters (2003):

n [adj, adv[fn:adv], v [adv]. *Function as biological activity*
  - n [adj, adv]: What an item does or is capable of doing (where the item is a component or subcomponent of a Darwinian individual)
    + (n) "The /function/ of the genetic sequence is to produce an siRNA transcript"
    + (adj) "The /functional/ effect of the genetic sequence is to produce an siRNA transcript"
    + (adv) "The /functionally/ relevant effect of the genetic sequence is to produce an siRNA transcript"
  - v [adv]: (For an item) to do something or to be capable of doing something (where the item is a component or subcomponent of a Darwinian individual)
    + (v) "The genetic sequence /functions/ to produce an siRNA transcript"
    + (adv) "The genetic sequence /functionally/ produces[fn:adv_v] an siRNA transcript"

n [adj, adv], v [adv]. *Function as biological role*
  - n [adj, adv]: A role played by a component that contributes to the capacity of a complex biological system contained within a Darwinian individual
    + (n) "The /function/ of the genetic sequence is to produce an siRNA transcript, which in turn acts to degrade mRNA"
    + (adj) "The /functional/ effect of the genetic sequence is to produce an siRNA transcript, which in turn acts to degrade mRNA"
    + (adv) "The /functionally/ relevant effect of the genetic sequence is to produce an siRNA transcript, which in turn acts to degrade mRNA"
  - v [adv]: (For an item) to perform a role that contributes to the capacity of a complex biological system contained within a Darwinian individual
    + (v) "The genetic sequence /functions/ to produce an siRNA transcript, which in turn acts to degrade mRNA"
    + (adv) "The genetic sequence /functionally/ produces an siRNA transcript, which in turn acts to degrade mRNA"

(Note that although the /specific/ complex system is not identified explicitly (i.e. we don't know the specific pathway being affected), this is function as biological role because it explicates /how/ the siRNA is used in a complex biological system.)

n [adj, adv], v [adv]. *Function as biological advantage*
  - n [adj, adv]: An item's effect in a system that (either directly or indirectly)[fn:dir_indir] gives a biological advantage (or disadvantage)[fn:bio_disadv] to the Darwinian individual in which the system is contained.
    + (n) "The /function/ of the genetic sequence is to produce an siRNA transcript, which in turn acts to degrade mRNA, providing protection for /C. elegans/ against viral infections.
    + (adj) "The /functional/ effect of the genetic sequence is to produce an siRNA transcript, which in turn acts to degrade mRNA, providing protection for /C. elegans/ against viral infections."
    + (adv) "The /functionally/ relevant effect of the genetic sequence is to produce an siRNA transcript, which in turn acts to degrade mRNA, providing protection for /C. elegans/ against viral infections.
  - v [adv]: (For an item) to affect a system in a way that (either directly or indirectly)[fn:dir_indir] benefits the Darwinian individual in which the system is contained
    + (v) "The genetic sequence /functions/ to produce an siRNA transcript, which in turn acts to degrade mRNA, providing protection for /C. elegans/ against viral infections.
    + (adv) "The genetic sequence /functionally/ produces an siRNA transcript, which in turn acts to degrade mRNA, providing protection for /C. elegans/ against viral infections.

n [adj, adv], v [adv]. *Function as selected effect*
  - n [adj, adv]: An item's effect that contributed to historical selection for, or maintenance of, the item in Darwinian individuals
    + (n) "The /function/ of the genetic sequence is to produce an siRNA transcript because protecting against viral infections was selected for in /C. elegans/ populations."
    + (adj) "The /functional/ effect of the genetic sequence is to produce an siRNA transcript because protecting against viral infections was selected for in /C. elegans/ populations."
    + (adv) "The /functionally/ relevant effect of the genetic sequence is to produce an siRNA transcript because protecting against viral infections was was selected for in /C. elegans/ populations."
  - v [adv]: (For an item) to have contributed to historical selection for, or maintenance of, the item in Darwinian individuals
    + (v) "The genetic sequence /functions/ to produce an siRNA transcript because protecting against viral infections was selected for in /C. elegans/ populations."
    + (adv) "The genetic sequence /functionally/ produces an siRNA transcript because protecting against viral infections was selected for in /C. elegans/ populations."

n [adj, adv], v [adv]. *Function as producing (or not producing) a biological activity*[fn:activity]
  - n [adj, adv]: An item that is producing a biological activity in accordance with expectations
    + (n) "Liver /function/ is important", "Liver /dysfunction/ is associated with excessive alcohol intake"
    + (n: gerund) "/Functioning/ is important for the liver"
    + (n: present participle) "A /functioning/ liver is important", "The liver is /functioning/ as expected"
    + (adj) "A /functional/ liver is important", "A /non-functional/ liver is associated with excessive alcohol intake"
    + (adv) "A /functionally/ useful liver is important", "A pseudogene that is not transcribed is /functionally/ redundant"
  - v [adv]: (For an item) to produce a biological activity in accordance with expectations
    + (v) "The liver /functions/ without issues", "The liver /functions/ improperly.
    + (adv) "The liver operates /functionally/", "The liver does not operate /functionally/ .

n [adj, adv], v [adv]. *Function as performing (or not performing) its biological role*
  - n [adj, adv]: An item that is performing its biological role in accordance with expectations[fn:perform_role]
    + (n) "Liver /function/ is important for the hepatic system", "Liver /dysfunction/ is associated with excessive alcohol intake in humans"
    + (n: gerund) "/Functioning/ is important in order for the liver to play a role in the hepatic system"
    + (n: present participle) "A /functioning/ liver is important for the hepatic system", "A liver is /functioning/ as expected in the hepatic system"
    + (adj) "A /functional/ liver is important for the hepatic system", "A /non-functional/ liver is associated with excessive alcohol intake in humans"
    + (adv) "A /functionally/ useful liver is important for the hepatic system"
  - v [adv]: (For an item) to perform its biological role in accordance with expectations
    + (v) "The liver /functions/ in most humans", "In some humans, the liver /functions/ improperly.
    + (adv) "The liver operates /functionally/ in most humans", "In some humans, the liver is /functionally/ impaired.

(The difference between these two senses of function as perform/work is whether a complex system is identified, which is also the difference between activity and role.)

n [adj, adv], v [adv]. *Function as producing (or not producing) a biological advantage*
  - n [adj, adv]: An item that is performing its biological role, producing a biological advantage in accordance with expectations[fn:produce_adv]
    + (n) "Liver /function/ is important for human health[fn:human_health]", "Liver /dysfunction/ is associated with excessive alcohol intake and liver disease[fn:disease]"
    + (n: gerund) "/Functioning/ is important in order for the liver to aid human health"
    + (n: present participle) "A /functioning/ liver improves the efficiency of the hepatic system[fn:efficiency]", "For human health, the liver needs to be /functioning/ as expected in the hepatic system"
    + (adj) "A /functional/ liver is important for human health", "A /non-functional/ liver is associated with excessive alcohol intake and impairs the hepatic system"
    + (adv) "A /functionally/ useful liver is important for human health"
  - v [adv]: (For an item) to perform its biological role, producing a biological advantage in accordance with expectations
    + (v) "In healthy patients, the liver /functions/ without issues", "In unhealthy patients, the liver /functions/ improperly.
    + (adv) "In healthy patients, the liver operates /functionally/", "In unhealthy patients, the liver is /functionally/ broken.

n [adj, adv], v [adv]. *Function as performing (or not performing) its selected effect*
  - n [adj, adv]: An item that is performing the biological role for which it was selected
    + (n) "Zebra stripe /function/ helps reduce attacks from biting flies"
    + (n: gerund) "/Functioning/ is important in order for zebra stripes to reduce attacks from biting flies"
    + (n: present participle) "/Functioning/ zebra stripes can reduce attacks from biting flies"
    + (adj) "/Functional/ zebra stripes can reduce attacks from biting flies"
    + (adv) "/Functionally/ useful zebra stripes can reduce attacks from biting flies"
  - v [adv]: (For an item) to perform the biological role for which it was selected
    + (v) "Zebra stripes /function/ if they reduce attacks from biting flies"
    + (adv) "Zebra stripes perform /functionally/ if they reduce attacks from biting flies"

*Ecological function*
  - For each of the above 8 cases, there are ecological equivalents.
  - For biological function, /x/ is a component of a Darwinian individual /i/, and /z/ (if present) is a containing system of /x/ (either an /i/ or a complex system within an /i/).
  - For ecological function, /x/ is an /i/, or an assemblage of interacting /i/ s (group, population, species, ecosystem, etc.), and /z/ (if present) is a containing system of /x/ (assemblage of interacting /i/ s)

*Technical use*
  - Use of function that is highly technical and cannot easily be unpacked
    + "functional connectivity", "functional biology", "subfunctionalization", "neofunctionalization", etc.

Finally, in some cases, we simply don't have enough information to understand the sense in which function is being used even after unpacking. 
There are several configurations that can lead to this situation.
If the item cannot be identified, we will classify as *unidentifiable item*.
If the item can be identified, but meaning cannot be ascertained, we will classify as *unidentifiable meaning: effect specified* if the item's effect is specified and *unidentifiable meaning: effect unspecified* if the item's effect is unspecified.

This gives the following list of categories:

  1. *function as biological activity*
  2. *function as biological role*
  3. *function as biological advantage*
  4. *function as selected effect*
  5. *function as ecological activity*
  6. *function as ecological role*
  7. *function as ecological advantage*
  8. *function as ecological selected effect*
  9. *function as producing biological activity*
  10. *function as performing biological role*
  11. *function as producing biological advantage*
  12. *function as performing selected effect*
  13. *function as producing ecological activity*
  14. *function as performing ecological role*
  15. *function as producing ecological advantage*
  16. *function as performing ecological selected effect*
  17. *technical*
  18. *unidentifiable item*
  19. *unidentifiable meaning: effect specified*
  20. *unidentifiable meaning: effect unspecified*
  21. *mathematics*
  22. *non-biological role or purpose*
  23. *performing non-biological role or purpose*
  24. *relational*
  25. *social event*
  26. *programming*

[fn:adv] I have yet to encounter a scenario in which an adverbal form of function---functionally is the only one that I can think of---modifies a verb (e.g. something like "the gene is functionally transcribed"). Instead it typically modifies an adjective (e.g. "functionally important"). But for completeness I have added modification of a verb as a possibility.
[fn:adv_v] Pretty good example of why we don't encounter this form, as it is a torturous construction.
[fn:dir_indir] Directly or indirect has two meanings, namely: (i) indirect or direct fitness benefits to the individual (e.g. inclusive fitness) and (ii) the phenotype might directly affect fitness (e.g. zebra stripes) or it might indirectly affect fitness by contributing to a phenotype (e.g. a gene involved in pigment production contributes to a mimicry phenotype). For (i), the system /z/ needs to be either the organism or a system of the organism; however, the advantage to the organism could be gained via interactions beyond the organism (e.g. a gene for altruism will affect a complex system within an organism, but the fitness advantage to the organism is realised through interactions of the focal organism and its social partners).
[fn:bio_disadv] Since "biological advantage" considers how a trait contributes to the capacity of a complex system, where the capacity of the system gives a biological (ultimately fitness) advantage, it is inherently a counterfactual notion (i.e. comparing how something compares against a probable or imagined alternative). A biological disadvantage therefore simply switches which item has the biological advantage, which at our grain of analysis is effectively equivalent (what we are trying to understand with "biological advantage" is when biologists are using function to refer to an item affecting the performance of an organism, which is the case both for "advantage" and "disadvantage" ascriptions).
[fn:activity] This sense of function captures a number of terms associated with not performing as expected (non-functional, dysfunction, malfunction, loss of function, etc.).
[fn:perform_role] We will need to give some thought into exactly what is implied by "in accordance with expectations" here. The biological role category doesn't imply that an item "ought to" do anything. Nevertheless, one can have an expectation that an item has a biological role or a set of biological roles (the concept doesn't make much sense otherwise). If the item does not perform its biological role in a particular circumstance (e.g. the item is defective), then one might talk about how this (defective) token of an item is not performing its biological role.
[fn:produce_adv] This one is the trickiest to make sense of the four in a produce/perform sense. It's effectively function as performing biological role but with the addition of there being an expectation that performing the biological role as expected will benefit an organism relative to a counterfactual in which the biological role is not being performed as expected (e.g. a malfunction of sorts with the biological role such that it does not produce the biological advantage as expected). We'll definitely need some worked-out examples of this to clarify what we mean because it's not easy to define /a priori/ what falls under "produce the biological advantage as expected".
[fn:human_health] Here I'm making the judgement that "health" is a normative statement about how well a human is performing (with a binary classification of "disease" for everything below a threshold and "health" for everything above that threshold). Implicitly, the counterfactual here is a human with a non-functioning liver. This is subtly different to the way that the counterfactual comparison works for the case of function as biological advantage. In this latter case, the counterfactual comparison is that of our trait of interest and a (real or imagined) competing trait (e.g. zebras with stripes vs. zebras with no stripes). In the case of "health", or more generally function as producing a biological advantage, the counterfactual comparison is that of a functioning version of our trait of interest (e.g. liver) and a non-functioning version of our trait of interest.
[fn:disease] This is the flip-side of "health". The expectation is that if the biological role is performed properly, then "health" will result; if the biological role is not performed properly (i.e. the mechanism is dysfunctional), then "disease" results.
[fn:efficiency] This one is more subtle than the human health case, but one could argue that because the liver "working as expected" improves the efficiency of the hepatic system, this implicitly benefits an organism with a functioning liver relative to a counterfactual organism with a less-efficiently-functioning liver. This is a good example for why we need to come up with a comprehensive list of examples that we decide by consensus meet the threshold for normative language. We can then use these examples to arbitrate future cases.

* Operational definition/classification scheme for function
** General comments on "unpacking" function
It can be difficult to parse the semantics of function because of the wide variety of syntactical structures in which it is found (compare the following snippets: "the gene functions to", "the function of the gene is", "the functional gene", "the functioning gene", "the functionality of the gene", "the gene is functional", "the functional impact of the gene", "functional impact on gene function", "the gene is functionally important", etc.).
An important step, therefore, is to strip away any redundant, extraneous, or otherwise confusing aspects of the syntactical structure to get at the semantics of function.

As highlighted in the previous section, function can be used in a wide range of senses.
It is (relatively) simple to deal with those cases in which function is used in a highly technical sense or in which function is used in a mathematical, computational routine, or relational sense.
It is more difficult to disambiguate when function is used in the sense of activity or role ("the gene functions to") versus when function is used in the sense of performing activity or role ("the gene functions as expected").
Despite these being two very different semantic senses, they can be very difficult to tell apart in real-world usages.

Our approach therefore will be to unpack sentences, recasting them in a standard form with the verb /functions/.
We treat *function as biological activity*, *function as biological role*, and *function as biological advantage* as being on an ordered continuum.
By this, we mean that if certain conditions are met, then *activity* can be superseded by *role* or *advantage*, and *role* can be superseded by *advantage*.
To show how this works, we first define the necessary conditions for a phrase to be classified as *function as biological advantage* and work our way down from there.

We say that a sentence about an item /x/ is used in the sense of *function as biological advantage* if it can be unpacked into the following form: /x/ functions to do /y/ in /z/, where /x/ is a component of a complex system /z/, /z/ is a system found in a Darwinian individual /i/, and /x's/ performance of /y/ in /z/ is advantageous for /i/ (relative to an explicitly-identified or implied alternative to /x/). The advantage for /i/ might be direct or indirect (e.g. group selection or inclusive fitness). This differs from function as biological role in that we can answer questions such as "how is /x/'s effect (/y/) on /z/ beneficial (or detrimental) to the organism?". /z/ needs to be explicitly identifiable but need not be /specifically/ identified (refer to the earlier examples of biological advantage with siRNA degrading mRNA---it is sufficient to specify function in a gene regulatory network without identifying /which/ regulatory network).

We say that a sentence about an item /x/ is used in the sense of *function as biological role* if it can be unpacked into the following form: /x/ functions to do /y/ in /z/, where /x/ is a component of a complex system /z/, and /z/ is a system found in a Darwinian individual /i/. This differs from function as biological activity in that we can answer questions such as "how is /x/ used in /z/?".

We say that a sentence about an item /x/ is used in the sense of *function as biological activity* if it can be unpacked into the following form: /x/ functions to do /y/, where /x/ is a component (or subcomponent) of a Darwinian individual /i/.

We say that a sentence about an item /x/ is used in the sense of *function as selected effect* if it can be unpacked into the following form: /x/ functions to do /y/ such that doing /y/ in the past caused /x/ to be selected for or maintained in a population (relative to an actual or counterfactual historical alternative or set of alternatives to /x/).
Indicators that we are dealing with function as selected effect are function being invoked in an etiological/explanatory context (of the "the function explains why the trait exists" type), language associated with "selection" or "selected for", and reference to function in the context of evolutionary theories (e.g. natural selection, sexual selection, kin selection, genetic/genomic conflict, sexual conflict, reproductive strategies, frequency-dependence, etc.).

If we cannot unpack the sentences according to one of the above schemes, then there are two possibilities: (i) function is used in the sense of activity/role/advantage/selected effects but the sentence is incompletely specified (*unidentifiable item*, *unidentifiable meaning: effect specified, *unidentifiable meaning: effect unspecified*); (ii) function is used in the sense of *function as producing biological activity*, *function as performing biogical role*, *function as producing biological advantage*, or *function as performing selected effect* (each of which could also be incompletely specified).
For use of function in the sense of (ii), we have a couple of potential approaches (I'll use *produce/perform* as shorthand for these four cases).

One form that we see fairly often is for function in the sense of *produce/perform* to be attached to the containing system rather than the component.
Consider for example the sentence "liver function is affected by gene A expression".
It is incorrect to unpack this sentence into the form "gene A expression functions to affect the liver" because function is used to modify liver not gene A.
The important thing to note here is that in this sentence liver refers to the containing system not a component of a wider containing system (contrast to the statement "the liver functions to do /y/ in the hepatic system").
Gene A can be viewed as a component but we cannot attribute function to it as function modifies liver, the containing system, not gene A.
Now, of course, given hierarchical biological organisation, whether something is a containing system or a component is a relative notion.
The above process is therefore a useful indicator that something is being used in the sense of *produce/perform*, but it is not a sufficient indicator.
For example, if the sentence was instead "liver function, which is important for the hepatic system, is affected by gene A expression", the liver is now both a containing system (of gene A) and a component (of the hepatic system).
But even if we try to unpack this expanded sentence in which liver can be a component, we get "the liver functions to ___ in the hepatic system".
Again we identify a problem, namely that the "action" part of the sentence is connected to gene A not the liver (gene A does something, namely express an RNA transcript whereas the liver does not do anything).
Since function modifies liver, which does not have an identifiable activity/role in a wider containing system, this is not a candidate for function as activity/role/advantage/selected effect; it is, however, a candidate for *produce/perform*.
This is the defining characteristic of function being used in the *produce/perform* sense (or at least my working hypothesis of this): there is no identifiable candidate for the function (/y/).
To test this, we want to substitute "x function" with "how well x performs" or "how well x works" into the original sentence.
If the substitution does not alter the sentence's semantics then we will classify as one of *produce/perform*.
If it does alter meaning, is ambiguous, or is difficult to parse, then we will classify as *unidentifiable meaning: effect unspecified*.
In the example above, "liver function is affected by gene A expression" becomes "how well the liver works is affected by gene A expression", which seems unambiguous and semantically equivalent and so we would classify as *produce/perform*.

To summarise, in order to disambiguate function in the sense of *produce/perform*, we will cast into the unpacked form: /x/ functions to do /y/ ..., where /x/ is the item referred to by function (note that for some variations of function, this might require some preprocessing in order to cast into this form).
If /x/ does not have an identifiable role, this is an indicator that function is being used in the sense of *produce/perform*.
For these cases, if we substitute "/x/ function" with "how well /x/ performs" (or an analogous substitution, depending on the particular syntatic construction/variant of function) with no loss of meaning, then classify as *produce/perform*.

The difference between *function as producing biological activity* and *function as performing biological role* is whether a system /z/ is specified. The difference between *function as performing biological role* and *function as producing biological advantage* is whether there is a specified connection between performing the biological role and a normative aspect of the organism's performance. *Function as performing selected effect* is distinguished by its focus on an item performing a biological role that has been shaped by selection.

The ecological function equivalents to the biological function equivalents differ with regard to the types of items specified for /x/ and /z/, as explained earlier and in the flowchart below.

** Flowchart/workflow for unpacking and disambiguating function sentences
    1. Non-biological senses of function
       - 1.1 Is function used in a *technical*, *mathematics*, *non-biological role or purpose*, *performing non-biological role or purpose*, *relational*, *social event*, or *programming* sense? If so, classify and EXIT; if not, go to step 2.1.
    2. Identify the part of speech
       - 2.1. Is function (or a variant) being used in a standalone form[fn:4] (e.g. a simple noun as in "The function of gene A is ...", or a verb as in "Gene A functions to ..."). If yes, go to step 2.2; if no, go to step 3.1.
       - 2.2. Can a candidate for /x/ be identified? If no, classify as *unidentifiable item* and EXIT. If yes, go to step 2.3.
       - 2.3. Is /x/ an abstract noun? If yes, go to step 3.6. If no[fn:conc], go to step 3.7.
    3. Detailed unpacking of function (or variant)[fn:6]
       - 3.1. Is function being modified by another part of speech (e.g. another noun as in "protein function" or an adjective as in "transcriptional function")? If yes, go to step 3.2; if no (it modifies another part of speech such as in "functional spores"), go to step 3.4.
       - 3.2. Is the part of speech that modifies function sufficiently concrete? If yes (e.g. "transcriptional function"), go to step 3.3; if no (e.g. "important function"), treat function as a simple noun and go to step 2.2.
       - 3.3. Is the part of speech that modifies function the best candidate for /x/ (e.g. "protein function", which could be unpacked as "The protein functions to...")? If yes, go to step 3.7 (noting /x/). If no, go to step 3.6.
       - 3.4. Identify the noun/adjective/adverb that the variant of function modifies and rearrange into the form "<modified noun> functions to ..."; go to step 3.5.
       - 3.5. Is the <modified noun> sufficiently concrete (e.g. gene, liver) or is it abstract or an adjective/adverb (e.g. effects, important)? If abstract, go to step 3.6; if concrete, go to step 3.7
       - 3.6. Can you identify a sufficiently concrete noun (candidate for /x/) that the <function variant + modified part of speech> clause modifies (e.g. in "The gene is functionally important", the abverb "functionally" modifies the adjective "important" and "functionally important" modifies the concrete noun "gene)? If no, classify as *unidentifiable item* and EXIT; if yes, go to step 3.7 (noting /x/ and treating <function variant + abstract modified part of speech> as a simple verb (e.g. unpacking "The gene is functionally important" as "The gene functions to...")).
       - 3.7. Manipulate sentence into unpacked form "/x/ functions to do /y/ in /z/...". Can /y/ be identified[fn:y_from33]? If yes, go to step 4.1. If no, or if the variant of function being used is directly evaluative (e.g. /dysfunctional/, /non-functional/, /loss of function/, /malfunction/, etc.), go to step 5.1.
    4. Candidates for biological activity/role/advantage/selected effect
       - 4.1. Can it be unpacked into the following form: /x/ functions to do /y/ such that doing /y/ in the past caused /x/ to be selected for or maintained in a population (relative to an actual or counterfactual historical alternative or set of alternatives to /x/)? If yes and /x/ is a component of a Darwinian individual /i/, classify as *function as selected effect* and EXIT; if yes and /x/ is an /i/ or an assemblage of interacting /i/ s (group, population, species, ecosystem, etc.), classify as *function as ecological selected effect* and EXIT; if no go to 4.2.
       - 4.2. Can it be unpacked into the following form: /x/ functions to do /y/ in /z/, where /x/ is a component of a complex system /z/, /z/ is a Darwinian individual /i/ or a complex system within /i/, and /x's/ performance of /y/ in /z/ is advantageous for /i/ (relative to an explicitly-identified or implied alternative to /x/)? If yes, classify as *function as biological advantage* and EXIT. Can it be unpacked into the following form: /x/ functions to do /y/ in /z/, where /x/ is an /i/ or an assemblage of interacting /i/ s[fn:ecol], /z/ is a containing system of /x/ (an assemblage of interacting /i/ s such as a group, population, species, ecosystem, etc.), and /x/'s performance of /y/ is advantageous for /z/[fn:ecol2] (relative to an explicitly-identified or implied alternative to /x/)? If yes classify as *function as ecological advantage* and EXIT. If no, go to step 4.3.
       - 4.3. Can it be unpacked into the following form: /x/ functions to do /y/ in /z/, where /x/ is a component of a complex system /z/, and /z/ is a Darwinian individual /i/ or a complex system within /i/? If yes, classify as *function as biological role* and EXIT. Can it be unpacked into the following form: /x/ functions to do /y/ in /z/, where /x/ is an /i/ or an assemblage of interacting /i/ s, and /z/ is a containing system of /x/ (an assemblage of interacting /i/ s such as a group, population, species, ecosystem, etc.)? If yes, classify as *function as ecological role* and EXIT. If no, go to step 4.4.
       - 4.4. Can it be unpacked into the following form: /x/ functions to do /y/, where /x/ is a component (or subcomponent) of a Darwinian individual /i/"? If yes, classify as *function as biological activity* and EXIT. Can it be unpacked into the following form: /x/ functions to do /y/, where /x/ is a /i/ or an assemblage of interacting /i/ s (group, population, species, ecosystem, etc.)? If yes, classify as *function as ecological activity* and EXIT. If no, classify as *unidentifiable meaning: effect specified* and EXIT.
    5. Candidates for function as performing or producing activity/role/advantage/selected effects
       - 5.1. Confirm that /y/ cannot be identified in the unpacked form (if it can, either you have made a mistake or there is a mistake with the flowchart). Assuming /y/ cannot be identified, go to step 5.2.
       - 5.2. Substitute "/x/ function" with "how well /x/ performs" (or an analogous substitution, depending on the particular syntatic construction/variant of function) into the /raw sentence/ (not the unpacked sentence). If there is loss of meaning or ambiguity, classify as *unidentifiable meaning: effect unspecified*; if there is no loss of meaning and no ambiguity, go to step 5.3.
       - 5.3. Does the sentences's language indicate that the biological role has been shaped by selection? If so, and /x/ is a component of a Darwinian individual /i/, classify as *function as performing selected effect* and EXIT. If so, and /x/ is an /i/ or an interacting assemblage of /i/ s, classify as *function as performing ecological selected effect* and EXIT. If not, go to step 5.4.
       - 5.4. Can you identify /z/ (complex containing system) in the unpacked sentence? If yes, go to step 5.5; if not, and /x/ is a component of a Darwinian individual /i/, classify as *function as producing biological activity*[fn:produce_activity] and EXIT. If not and /x/ is a Darwinian individual /i/ or an interacting assemblage of /i/ s, classify as *function as producing ecological activity* and EXIT.
       - 5.5. Is the performance of the biological role associated with how well the complex system (or organism containing the complex system) performs (e.g "Liver functioning affects /human health/")? If yes, and if /x/ is a component of a Darwinian individual /i/ and /z/ is a Darwinian individual /i/ or a complex system within /i/, classify as *function as performing biological advantage*. If yes, and if /x/ is an /i/, or an assemblage of interacting /i/ s, and /z/ is an interacting assemblage of /i/ s (group, population, species, ecosystem, etc.), classify as *function as performing ecological advantage*. If no (e.g. "Liver functioning is important for the hepatic system"), and if /x/ is a component of a Darwinian individual /i/ and /z/ is an /i/ or a complex system within /i/, classify as *function as producing biological role*. If no, and /x/ is an /i/ or an assemblage of interacting /i/ s and /z/ is an interacting assemblage of /i/ s (group, population, species, ecosystem, etc.), classify as *function as producing ecological role*. EXIT.

[fn:4] By "standalone form", I mean that function is not directly modifying another part of speech (e.g. "functional effects") nor directly being modified by another part of speech (e.g. "protein function")
[fn:conc] I'm referring to these as "sufficiently concrete", which means that the noun is a candidate for a item/trait/character. Consult Monika to make this consistent with linguistics terminology. (what follows is pasted from an old footnote) I now differentiate between concrete nouns that have /y/ specified/non-specified to direct between activity/role/adv/se and produce/perform (resolves the "functional spore" case). But note that these cases could be a bit ambiguous when it comes to identifying /y/. For example, if we had something like "Gene A's expression affects liver function, namely how efficiently it breaks down metabolites, in the hepatic system." Given the current workflow, "liver" is /x/, "breakdown metabolites" is /y/, "hepatic system" is /z/ and so this is *function as biological role*. But if it were instead "Gene A's expression affects liver function in the hepatic system", "liver" is /x/, /y/ is missing, "hepatic system" is /z/ and so this is *function as performing biological role*. But arguably the semantics of the two sentences are the same (at least intuitively to me it seems like the first case is also *function as performing biological role*). The current workflow effectively says that function as activity/role/adv/se trumps function as performing/producing, which may be fine but it may not. For the moment, I'm going to leave this unresolved, but try to make a note of any cases in which determining /y/ is ambiguous. (Additional thoughts from email. If we change the first example slightly to "Gene A's expression affects how well the liver functions, namely its ability to break down metabolites, in the hepatic system." I think the main meaning is clearly function as performing biological role. Yet it also clearly identifies a biological role (y) for liver. Indeed, the current workflow identifies it as function as biological role because function modifies liver (/x/), /y/ is clearly break down metabolites, and /z/ is hepatic system. To be fair, I don't think we are making a large mistake either way here, as arguably it is a case with both senses with preference for function as performing biological role. These examples might be vanishingly rare in real cases, so perhaps we just say that when both senses are used we preference the function as biological activity/role/advantage. Perhaps this can be addressed by fleshing out the "how to identify /y/" instructions.)
[fn:6] Function should be either being used as an adjective ("the gene is functional"), adjective phrase ("the gene is of functional importance"), nominative phrase ("the functional gene" or "protein function"), adverb ("the gene is functionally important") or adverbal phrase ("the functionally-important gene". Need to check with Monika to make sure that these options are linguistically accurate and to make sure that we phrase this in a formally-correct manner. For our purposes though, this basically applies to anything outside of the simple noun and verb cases.
[fn:y_from33] Note that if coming via 3.3, /y/ might be part of the nominative function phrase (e.g. "transcriptional function of the gene", which could be unpacked as "The gene functions to transcribe...")
[fn:ecol] This restriction on /x/ does lead to one class remaining ambiguous. Consider the case where /x/ is a component of system /z/ in organism /i/ but the sentence reads something like "/x/ functions to do /y/ in /z/, which increases ecosystem productivity of groups of /i/ s". This should either be function as ecological advantage or function as biological role (it isn't function as biological advantage because the advantage is not couched as a fitness advantage to /i/ but rather as an advantage of the group as a whole). It would be classified as biological advantage but has no option to be classified as function as ecological advantage because of the restriction on /x/ of having to be an /i/ or interacting assemblage of /i/ s. This might be fine or it might be something we need to address. Seems like a fairly uncommon scenario in any case.
[fn:ecol2] The analogy with biological advantage starts to break down here. Whereas biological advantage refers to advantages to the /organism/, ecological advantage refers to advantages to the /system/. Consider a group of organisms. Biological advantage might show how a trait benefits an organism indirectly through social interactions; ecological advantage would talk about benefits to the group. This might need to be tweaked, however, as I'm not sure whether the "/z/ as a containing system of /x/" and the "/z/ as the system being benefited" must be identical.
[fn:produce_activity] In order to be classified as such, it is sufficient for /x/ to be a candidate for a trait, which means that something as simple as "liver function" is technically sufficient. However, because of the criterion in step 5.2 that there not be loss of meaning or ambiguity after the substitution, in practice the sentence will need to be quite a bit more complex (as otherwise there is no way to establish that the substitution retains equivalent meaning).
* Outstanding issues for the classifying function handbook
  - Continue to monitor for cases that the flowchart misclassifies
  - Clearer instructions for identifying /y/ in cases in which there is ambiguity (the islets (email) and "Gene A's expression affects how well the liver functions, namely its ability to break down metabolites, in the hepatic system." examples)
  - Handful of detailed (and different) worked-out examples for function as biological/ecological activity/role/advantage/selected effects
  - Handful of detailed (and different) worked-out examples for function as performing/producing biological/ecological activity/role/advantage/selected effects
  - Examples of function as biological advantage and close-but-rejected cases to aid ruling on the normative language requirement
  - Examples of function as selected effects and close-but-rejected cases to aid ruling on the evolutionary/etiological language requirement
  - Examples of function as producing biological advantage and close-but-rejected cases to aid ruling on the normative language requirement
  - Examples of function as performing selected effects and close-but-rejected cases to aid ruling on the evolutionary/etiological language requirement
  - List of the sort of language/terms that have been used to rule on the normative language requirement of biological advantage
  - List of the sort of language/terms that have been used to rule on the evolutionary/etiological language requirement of selected effects
* notes on syntatical structure
** 20200205 notes from meeting with Monika
  - can test for a nominal phrase by substituting with a pronoun (it, this, etc.)
  - nominal phrase construction is premodifier(s)-head-postmodifier(s)
  - can use branching to divide nominal phrase into smaller nominal phrases
  - we should add another decision tree to step 3 where we cast a sentence into a nominal phrase or rearrange nominal phrase if necessary (e.g. for recasting, "uterine glands are functional" to "functional uterine glands" where "glands" is head, "uterine" is "modifier" of glands, and "functional" modifies the nominal phrase "uterine glands"; for rearranging, "protein functional evolution" into "functional protein evolution")
  - we essentially have 3 layers--syntactical, in which we try to get around the varieties of syntatic structures by unpacking into a standard form, general semantic for things like separating "abstract" and "concrete" nounts, and discipline-specific semanatic, in which after unpacking into a standard form we still need to interpret the authors' intentions.
  - I will need to be more explicit about some of the syntatical structures (aside from the stuff discussed in this meeting, I also need to incorporate the stuff on functioning as gerund, present participle, functional, functionally, etc. into the flowchart)
** 20200205 notes from linguistic passages sent by Monika
  - the head of a nominal, adjective, or adverb phrase is the element that can replace the entire phrase without affecting sentence structure (e.g. "/New books on linguistics/ are very expensive"--"/Books/ are very expensive"; doesn't hold for verb phrases or prepositional phrases, as replacing the most important constituent here will not retain the structure, e.g. "John darted /from the room/"--"John darted /from/. Also for a verb phrase it is semantic considerations that determine which is the most important constituent (in a verb phrase, all elements are verbs); in a preposition phrase it is obviously the preposition that's the most important constituent)
    + preposition phrases are obviously important for us, as illustrated in a phrase like "the function of uterine glands", in which case the prepositional phrase /of uterine glands/, /of/ is said to govern the other constituent /uterine glands/.
    + in nominal, adjective, adverb, verb phrases, the relation between dominant member and other constituents is /subordination/
  - elements other than the head in a nominal phrase are /modifiers/ (/premodifiers/ if they precede the head; /postmodifiers/ if they follow the head). You can have multiple pre/post modifiers. If a premodifier is interrupted by the head, then it is a /discontinuous modifier/
  - another element of a nominal phrase is the /determiner/, whihc determines whether the referent of the noun phrase is definite or indefinite, whether one or more referents are intended, etc. (e.g. /The/ book that I need, /My/ best suit, /Every/ boy in my class, etc.). It's very rare for a determiner to not be realised in a noun phrase and it's rarely possible to leave it out without destroying structure; modifiers, however, can be left out (the latter is why one can replace a noun phrase by the head noun, although I guess this implies that you leave in the determiner when doing the substitution)
  - modifiers can be /descriptive/, which describes the referent of the noun phrase in terms of a particular quality (e.g. that /tall/ boy) or /classifying/, which denotes or creates a subclass of the head (e.g. a /polar/ bear, a /criminal/ court). descriptive modifiers can themselves be intensified (e.g. that /very/ tall boy), but classifying modifiers cannot
  - noun phrases typically realise functions as subject, direct object, indirect object, benefactive object, subject attribute, and object attribute.
  - prepositional phrase may postmodify a noun phrase (is it equivalent to say that a noun phrase may premodify a prepositional phrase?)
  - adverb can act as premodifier in adjective phrase (e.g. functionally important)
  - adjective can be used attributably (e.g. the functional gene) or used as a predicatively (e.g. the gene is functional) as either subject or object attribute
  - (not from the notes but important) nouns can be used attributatively (known as attributative noun, noun premodifier, noun adjunct, or converted adjective). An example is "protein function". I think it should always be the case that in a string of nouns like the first will be attributative while the last will be the head of the noun phrase
** thoughts related to syntactical unpacking of function
I need to make two broad modifications to the scheme:
1. Rearranging noun phrases to simplify unpacking of function (e.g. protein functional evolution is best written as functional protein evolution
2. Solidifying the syntactical unpacking and improving the vague language (modifies used incorrectly, etc.)
*** noun phrases 
I'll first consider when the base noun form "function" is used.
*Case 1*: function is either (i) the subject of the sentence or the head noun of a noun phrase that acts as the subject or (ii) used as a verb
Examples (noun): "The function of the gene is to ...", "The function is to...", "The important function of the gene is...", "Protein function is important for..."
Example (verb): "The gene functions to...",
These are straightforward cases, which match the "standalone form" that I had previously described them as (this terminology needs to be changed but the general principle remains unchanged).
For a case like "protein function" our candidate for /x/ is the attributative noun (protein)
In a case like "important function", in which we have a noun phrase in which function is the head noun and the modifiers are not a candidate for /x/, we can probably reliably throw away the modifiers (this is basically what I was trying to get at in a much more vague way). Contrast this to "attentional function" in which (although depends on context) "attentional" might be viewed as a candidate for /x/ ("attention") and we wouldn't throw it away.
In a case like "The important function of the gene is...", we have a prepositional phrase, in the preposition "of" /governs/ a modifier, which in this case is the noun phrase "the gene" of which the head is "gene". Together, this preposition phrase is a /postdependent/ (wikipedia adpositional phrase) of the noun phrase "important function" of which the head is "function". So in this case, the candidate for /x/ is the head noun of the noun phrase modifier of the prepositional phrase. We can throw away "important" (as it is an abstract modifier), leaving "the gene functions to do...".
Reread notes sent by Monika to see whether noun phrase can include a prepositional phrase
*Case 2*: function (used as a noun) is a pre- or post-modifier in a noun phrase that acts as the subject. (*is this even possible?*)
Possible example?: "working memory function" as part of "evidence of an involvement in working memory function by assuming". Could head be "memory"? Tricky one, but "function" also works as head. If we changed "working memory function" to "working protein function" then it seems clearer that function is the head.
*Case 3*: adjective (functional) used in an attributive manner as part of a noun phrase (i.e. function is acting as a premodifier). Note that for adjectives, we should probably state that they either work in a descriptive or classifying manner---I think you can make a case for both (e.g. "the functional gene" where functional /describes/ the gene or "the functional gene" where functional /classifies/ gene into category /functional/ (where the other category is non-functional)...arguably though functional could split the categories into "this is its function" and "this isn't its function"...actually functional must be descriptive as it can be intensified
but if we have functional in the sense of "this is its function" then it couldn't be intensified so this could be one way of telling them apart

Example: "The functional gene..." (premodifier, subject attribute, concrete head), currently unpacked as "the gene functions to..." (3.4->3.5->3.7)
Example: "The functional role..." (premodifier, subject attribute, abstract head), currently classified as unidentifiable item (3.4->3.5->3.6->unidentifiable item)
*Case 4* adjective (functional) used in a predicative manner as lone adjective
Example: "The gene is functional..." (also subject attribute)
The cases 3 and 4, seems like we could just recast the sentence in the attributative form (semantically, seems like "the gene is functional" is equivalent to "the functional gene")
*Case 5* adjective (functional) used in a predicative manner as premodifier (so part of noun phrase)
Example: "The gene is a functional component..."
This is definitely different. These are cases that will tend to head down the 5 path (function as performing...)---if this is repeatable, maybe we can take a shortcut there?

*Case 6* (functioning) Can be part of multipart verbs (e.g. "The gene is functioning" where "is" is the auxiliary verb and "functioning" the present participle), function as an adjective that describes a noun ("the functioning gene"), or function as a noun (gerund form) ("functioning is important for a gene").
- Seems like if it's part of a multipart verb, perhaps it could often be directly unpacked as "functions"? (I think we can still get "the gene is functioning" in the sense of "the gene is working"? by the 3.7 case being answered no)
- if used as an adjective, seems like it's equivalent to functional?
- if used as a noun, seems like we could just replace it with the noun form "function"? For example, for "ecosystem functioning"->"ecosystem function"->noun phrase with function as head and concrete attributative noun->"ecosystem functions to..."

*Case 7* (functionally) 

need to include the example of "the function is important" where "is" is a linking verb connecting function with important (want to treat this the same as "the important function"
similarly "the gene's function is important" we'd want in the form "the important function of the gene" or "the gene's important function"
just thinking about the order in which to process things...

a variant of function may also appear in the predicate (linked to a subject by a copula such as "is")
