#+TITLE: Three-dimensions of function

* Rough outline
Our goal is to understand how biologists use the word "function".
We are interested in a few things, including how researchers use "function", how this differs among subfields of biology, and how well use of function corresponds to the main philosophical views on biological function (we are also interested in how this has changed over time, how it is used in different sections of the text, how collocates differ, etc.).
* Definitions of function
Function is used in a variety of different ways, which makes this a particularly difficult word sense disambiguation problem.
We are of course primarily interested in the use of function in a manner consistent with philosophical or biological conceptions of function (as opposed to colloquial use).
Our starting point is the definitions of function in WordNet 3.1, which are:

Noun
1. S: (n) function, mathematical function, single-valued function, map, mapping ((mathematics) a mathematical relation such that each element of a given set (the domain of the function) is associated with an element of another set (the range of the function))

2. S: (n) function, purpose, role, use (what something is used for) "the function of an auger is to bore holes"; "ballet is beautiful but what use is it?"

3. S: (n) function, office, part, role (the actions and activities assigned to or required or expected of a person or group) "the function of a teacher"; "the government must do its part"; "play its role"

4. S: (n) function (a relation such that one thing is dependent on another) "height is a function of age"; "price is a function of supply and demand"

5. S: (n) function (a formal or official social gathering or ceremony) "it was a black-tie function"

6. S: (n) affair, occasion, social occasion, function, social function (a vaguely specified social event) "the party was quite an affair"; "an occasion arranged to honor the president"; "a seemingly endless round of social functions"

7. S: (n) routine, subroutine, subprogram, procedure, function (a set sequence of steps, part of larger computer program)

Verb
8. S: (v) function, work, operate, go, run (perform as expected when applied) "The washing machine won't go unless it's plugged in"; "Does this old car still run well?"; "This old radio doesn't work anymore"

9. S: (v) serve, function (serve a purpose, role, or function) "The tree stump serves as a table"; "The female students served as a control group"; "This table would serve very well"; "His freedom served him well"; "The table functions as a desk"

10. S: (v) officiate, function (perform duties attached to a particular office or place or function) "His wife officiated as his private secretary"

If we focus on semantics, and combine a couple of categories and parts of speech, then we can trim this to get:

(1). S: (n) (mathematics (a mathematical relation such that each element of a given set (the domain of the function) is associated with an element of another set (the range of the function)) *mathematical function*

(2, 3, 9, 10). S: (n, v) (what something is used for; actions expected of a thing; to serve a purpose; perform expected duties) *function as role or purpose*

(4). S: (n) (a relation such that one thing is dependent on another) *function as relation*

(5, 6). S: (n) (a social gathering) *function as social event*

(7). S: (n) (a set sequence of steps, part of larger computer program) *programming function*

(8). S: (v) (perform as expected when applied) *function as performing role or purpose*

The various technical definitions that I will introduce below generally fall under *function as role or purpose*.
Likewise, there is a biological analogue to *function as performing role or purpose*.
To separate colloquial use from technical use, I will redefine these as *non-biological function as role or purpose* and *non-biological function as peforming role or purpose* to apply to non-biological usages (e.g. "The table functions as a desk").

To the colloquial definitions above, we add the technical definitions:

n [adj, adv], v. *Function as biological activity*
  - n [adj, adv]: What an item does or is capable of doing (where the item is a biological component of a Darwinian individual)
    + (n) "The /function/ of the gene is to produce an RNA transcript"
    + (adj) "The /functional/ effect of the gene is to produce an RNA transcript"
    + (adv) "The /functionally/ relevant effect of the gene is to produce an RNA transcript"
  - v: (For an item) to do something or to be capable of doing something (where the item is a biological component of a Darwinian individual)
    + (v) "The gene /functions/ to produce an RNA transcript"

n [adj, adv], v. *Function as biological role*
  - n [adj, adv]: A role played by a component that contributes to the capacity of a complex biological system contained within a Darwinian individual
    + (n) "The /function/ of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/"
    + (adj) "The /functional/ effect of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/"
    + (adv) "The /functionally/ relevant effect of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/"
  - v: (For an item) to perform a role that contributes to the capacity of a complex biological system contained within a Darwinian individual
    + (v) "The gene /functions/ to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/"

n [adj, adv], v. *Function as biological advantage*[fn:1]
  - n [adj, adv]: An item's effect in a system that (either directly or indirectly)[fn:2] gives a biological advantage to the Darwinian individual in which the system is contained
    + (n) "The /function/ of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/ where /y/ benefits the organism"
    + (adj) "The /functional/ effect of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/ where /y/ benefits the organism"
    + (adv) "The /functionally/ relevant effect of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/ where /y/ benefits the organism"
  - v: (For an item) to affect a system in a way that (either directly or indirectly)[fn:2] benefits the Darwinian individual in which the system is contained
    + (v) "The gene /functions/ to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/"

[fn:1] Although this is phrased in terms of an advantage (or, alternatively in Garson's 2016 view, explicitly in terms of fitness-contribution), in practice this will refer to normative judgements that could also refer to biological disadvantage (since the advantage is often relative to a counterfactual, it is also possible to talk of a disadvantage relative to a counterfactual---the important point is that this usage of function is relating the effect of a biological role (either directly or indirectly) to an organismal-level effect that (either directly or indirectly) affects organism fitness.
[fn:2] Directly or indirect has two meanings, namely: (i) indirect or direct fitness benefits to the individual (e.g. inclusive fitness) and (ii) the biological advantage function phenotype can directly affect fitness (e.g. zebra stripes) or indirectly affect fitness (e.g. a gene that improves metabolic capacity will affect multiple organismal phenotypes; while the net effect could be to improve organismal fitness, the function effect does this indirectly through "higher level" phenotypes).

n [adj, adv], v. *Function as selected effect*
  - n [adj, adv]: An item's effect that contributed to historical selection for, or maintenance of, the item in Darwinian individuals
    + (n) "The /function/ of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/ where having historically done /y/ explains past selection for (or maintenance of) the gene"
    + (adj) "The /functional/ effect of the gene is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/ where having historically done /y/ in /x/ explains past selection for (or maintenance of) the gene"
    + (adv) "The /functionally/ relevant effect is to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/ where having historically done /y/ in /x/ explains past selection for (or maintenance of) the gene"
  - v: (For an item) to have contributed to historical selection for, or maintenance of, the item in Darwinian individuals
    + (v) "The gene /functions/ to produce an RNA transcript, which is translated into a protein and used in system /x/ to do /y/ where having historically done /y/ in /x/ explains past selection for (or maintenance of) the gene"

Note, since the adverbal form (/functionally/---any others?) seems to modify an adjective or nominal phrase rather than a verb, I've lumped its definition with noun/adjective.

n [adj, adv], v. *Function as performing (or not performing) biological activity or role*[fn:3]
  - n [adj, adv]: An item that is producing an effect, or performing its biological role, in accordance with expectations
    + (n) "Liver /function/ is important for human health", "Liver /dysfunction/ is associated with excessive alcohol intake"
    + (n: gerund) "/Functioning/ is important in order for the liver to aid human health"
    + (n: present participle) "A /functioning/ liver is important for human health", "A liver is /functioning/ as expected"
    + (adj) "A /functional/ liver is important for human health", "A /non-functional/ liver is associated with excessive alcohol intake"
    + (adv) "A /functionally/ useful liver is important for human health", "A pseudogene that is not transcribed is /functionally/ redundant"
  - v: (For an item) to produce an effect, or to perform its biological role, in accordance with expectations
    + (v) "In healthy patients, the liver /functions/ without issues", "In unhealthy patients, the liver /functions/ improperly.

[fn:3] This sense of function captures a number of terms associated with not performing as expected (non-functional, dysfunction, malfunction, loss of function, etc.).

*Technical use*
  - Use of function that is highly technical and cannot easily be unpacked)
    + "functional connectivity", "functional biology", "subfunctionalization", "neofunctionalization", etc.

We also need to consider a special case that I will term *invalid attribution*.
Sometimes, a use of function can be unpacked into a valid candidate for further classification as biological function, but the item to which the function is being attributed is not a valid candidate for a trait having a biological function. 
Consider the following sentence: "Plant species A functions to increase productivity within the ecosystem". 
This has a form consistent with biological role, aside from the fact that a plant species is not a component of a Darwinian individual. 
In these cases (i.e. biological roles being attributed to invalid items), we will classify these as *invalid attribution*.
I suspect this will almost always involve *function as biological activity* ("the function of a deer is..."), *function as biological role* ("the function of a deer in a herd is to..."), or *function as performing biological activity or role* ("ecosystem functioning is important for...").

Finally, in some cases, we simply don't have enough information to understand the sense in which function is being used even after unpacking. We will classify these as *incompletely specified*.

This gives the following list of categories:

  1. *function as biological activity*
  2. *function as biological role*
  3. *function as biological advantage*
  4. *function as selected effect*
  5. *function as performing biological activity or role*
  6. *technical use*
  7. *invalid attribution*
  8. *incompletely specified*
  9. *mathematics*
  10. *non-biological role or purpose*
  11. *performing non-biological role or purpose*
  12. *relational*
  13. *social event*
  14. *programming*

* Operational definition/classification scheme for function
*** Broad categories of use
The definitions above fall into four broad usage categories: (i) biological function as activity/role/advantage/selected effect; (ii) biological functioning as performing activity/role; (iii) usages of biological function that either can't be unpacked (technical use) or can be unpacked but are incompletely specified or have an invalid attribution; or (iv) usages of function unrelated to biology (mathematical, programmatic, relational, non-biological, etc.).

If (iii or iv), function is being used in a sense that is of less interest to us because it is either not used in a biological sense, or it forms part of a technical, unspecified or invalidly-attributed phrase from which we cannot extract meaning.
The first step is therefore to see whether use falls under category (iv) (unrelated to biology).
If so, exit flowchart; if not, the second step is to see whether use falls under category (iii) (*technical use*).
If so exist flowchart; if not, the third step is to determine whether use is of type (i) or (ii).
If (i), we further need to determine whether it falls under biological activity, role, advantage, or selected effect.
For both (i) and (ii) it is possible that function usage might be incompletely specified (i.e. we simply do not have enough information to determine semantics).
The flow chart needs to adequately distinguish between these three possibilities (function as activity/role/advantage/selected effects, function as performing activity/role, or incompletely specified).

*** Unpacking use of function
It can be difficult to parse the semantics of function because of the wide variety of syntactical structures in which it is found (compare the following snippets: "the gene functions to", "the function of the gene is", "the functional gene", "the functioning gene", "the functionality of the gene", "the gene is functional", "the functional impact of the gene", "functional impact on gene function", "the gene is functionally important", etc.).
An important step, therefore, is to strip away any redundant, extraneous, or otherwise confusing aspects of the syntactical structure to get at the semantics of function.

As highlighted in the previous section, function can be used in a wide range of senses.
It is (relatively) simple to deal with those cases in which function is used in a highly technical sense or in which function is used in a mathematical, computational routine, or relational sense.
It is more difficult to disambiguate when function is used in the sense of "activity or role" ("the gene functions to") versus when function is used in the sense of "performing activity or role" ("the gene functions as expected").
Despite these being two very different semantic senses, they can be very difficult to tell apart in real-world usages.

Our approach therefore will be to unpack sentences, recasting them in a standard form with the verb /functions/.
We treat *function as biological activity*, *function as biological role*, and *function as biological advantage* as being on an ordered continuum.
By this, we mean that if certain conditions are met, then *activity* can be superseded by *role* or *advantage*, and *role* can be superseded by *advantage*.
To show how this works, we first define the necessary conditions for a phrase to be classified as *activity*.
We classify a phrase as *activity* if it can be unpacked into the form "/x/ functions to do /y/", where /x/ is a component (of a Darwinian individual) and /y/ is an effect of /x/.
We classify a phrase as *role* if it can be unpacked into the form "/x/ functions to do /y/ in /z/", where /x/ is a component of a complex biological system /z/, /z/ is either a Darwinian individual or a system that forms part of a Darwinian individual, and /y/ is an effect of /x/ that contributes to a capacity of /z/.
We classify a phrase as *advantage* if it can be unpacked into the form "/x/ functions to do /y/ in /z/ where performance of /y/ in /z/ is advantageous for a Darwinian individual /i/ that contains /z/"

*Function as selected effect* is unpacked differently.
We now need to be able to unpack it into a form such as "/x/ functions to do /y/ such that doing /y/ in the past has caused /x/ to be selected (or maintained) in a population".
Indicators that we are dealing with *function as selected effect* are function being invoked in an etiological/explanatory context (of the "the function explains why the trait exists" type), or reference to evolutionary theories (e.g. natural selection, sexual selection, kin selection, genetic/genomic conflict, sexual conflict, reproductive strategies, frequency-dependence, etc.).

If we cannot unpack the sentences according to one of the above schemes, then there are two possibilities: (i) function is used in the sense of activity/role/advantage/selected effects but the sentence is incompletely specified; (ii) function is used in the sense of *function as performing biological activity or role* (which itself may be completely or incompletely specified).
We cannot know whether (i) is true without first considering (ii).
For use of function in the sense of *function as performing biological activity or role*, we have a couple of potential approaches.

One form that we see fairly often is for function in the sense of *performing* to be attached to the containing system rather than the component.
Consider for example the sentence "liver function is affected by gene A expression".
It is incorrect to unpack this sentence into the form "gene A expression functions to affect the liver" because function is used to modify liver not gene A.
The important thing to note here is that in this sentence liver refers to the containing system not a component of a wider containing system (contrast to the statement "the liver functions to do /y/ in the hepatic system").
Gene A can be viewed as a component but we cannot attribute function to it as function modifies liver, the containing system, not gene A.
Now, of course, given hierarchical biological organisation, whether something is a containing system or a component is a relative notion.
For example, if the sentence was instead "liver function, which is important for the hepatic system, is affected by gene A expression", the liver is now both a containing system (of gene A) and a component (of the hepatic system).
But even if we try to unpack this expanded sentence in which liver can be a component, we get "the liver functions to ___ in the hepatic system".
Again we identify a problem, namely that the "action" part of the sentence is connected to gene A not the liver (gene A does something, namely express an RNA transcript whereas the liver does not do anything).
Since function modifies liver, which does not have an identifiable activity/role in a wider containing system, this is not a candidate for function as activity/role/advantage/selected effect; it is, however, a candidate for *performing*.
To test this, we want to substitute "x function" with "how well x performs" or "how well x works" into the original sentence.
If the substitution does not alter the sentence's semantics, then we will classify as *performing*.
If it does alter meaning, or is ambiguous or difficult to parse, then we will classify as *incompletely specified*.
In the example above, "liver function is affected by gene A expression" becomes "how well the liver performs/works is affected by gene A expression", which seems equivalent semantically and so we would classify as *performing*.
